import type { CharacterDefinition } from './types';

export const characterRegistry = [
  {
    id: 'otti',
    name: 'Otti',
    tagline: 'خفيف، مشجّع، وبيفضل جنبك خطوة بخطوة.',
    description: 'Englotti’s main teacher and companion: warm, playful, patient, and focused on getting the learner speaking.',
    accent: '#F5477D',
    renderer: { kind: 'otti-svg', preset: 'otti', motionScale: 0.5 },
    persona: { style: 'warm, playful, patient, concise, encouraging without sounding childish' },
  },
  {
    id: 'fustuq',
    name: 'Fustuq',
    tagline: 'فكرة صغيرة وحماس كبير.',
    description: 'A bright little mascot who keeps the pace lively and celebrates brave attempts.',
    accent: '#8EB82B',
    renderer: { kind: 'svg-mascot', preset: 'fustuq', motionScale: 0.65 },
    persona: { style: 'bright, energetic, playful, concise, encouraging' },
  },
  {
    id: 'hakim',
    name: 'Hakim',
    tagline: 'هادي، متفهم، وسهل في الكلام.',
    description: 'A steady conversational partner who gives you space to think and finish your ideas.',
    accent: '#7E9586',
    renderer: { kind: 'svg-human', preset: 'hakim', motionScale: 0.28 },
    persona: { style: 'warm, thoughtful, patient, concise' },
  },
  {
    id: 'reem',
    name: 'Reem',
    tagline: 'دافئة، فضولية، ومشجعة دايمًا.',
    description: 'A friendly conversational partner who keeps the exchange moving with natural follow-up questions.',
    accent: '#D8A3AF',
    renderer: { kind: 'svg-human', preset: 'reem', motionScale: 0.35 },
    persona: { style: 'warm, curious, supportive, natural' },
  },
  {
    id: 'marwan',
    name: 'Marwan',
    tagline: 'مريح، سريع البديهة، ويحب التحدي.',
    description: 'A confident conversational partner who helps you explain your thinking instead of stopping at short answers.',
    accent: '#9A8570',
    renderer: { kind: 'svg-human', preset: 'marwan', motionScale: 0.4 },
    persona: { style: 'relaxed, witty, direct, encouraging' },
  },
  {
    id: 'amal',
    name: 'Amal',
    tagline: 'واضحة، مليانة طاقة، ومتفاعلة.',
    description: 'An upbeat conversational partner who helps you keep speaking when you hesitate or lose your words.',
    accent: '#AE96CD',
    renderer: { kind: 'svg-human', preset: 'amal', motionScale: 0.4 },
    persona: { style: 'energetic, clear, positive, concise' },
  },
  {
    id: 'ember',
    name: 'Ember',
    tagline: 'فضولي وخفيف الظل.',
    description: 'A curious fox with a quick, playful conversational rhythm.',
    accent: '#E87E37',
    renderer: { kind: 'svg-recipe', species: 'fox', motionScale: 0.65 },
    persona: { style: 'curious, playful, quick, friendly, concise' },
  },
  {
    id: 'louz',
    name: 'Louz',
    tagline: 'هادي وبيحب يسمعك.',
    description: 'A calm cat who leaves room for you to finish your thought before nudging the conversation forward.',
    accent: '#8EABC1',
    renderer: { kind: 'svg-recipe', species: 'cat', motionScale: 0.4 },
    persona: { style: 'calm, observant, patient, gently curious' },
  },
  {
    id: 'sugar',
    name: 'Sugar',
    tagline: 'لطيف ومليان حماس.',
    description: 'A lively rabbit who makes practice feel light while still keeping you talking.',
    accent: '#BC99BD',
    renderer: { kind: 'svg-recipe', species: 'rabbit', motionScale: 0.6 },
    persona: { style: 'cheerful, lively, kind, encouraging, concise' },
  },
  {
    id: 'bondoq',
    name: 'Bondoq',
    tagline: 'دافي وبيطمنك.',
    description: 'A reassuring bear with a relaxed pace for learners who need a little more thinking room.',
    accent: '#AF8057',
    renderer: { kind: 'svg-recipe', species: 'bear', motionScale: 0.35 },
    persona: { style: 'reassuring, warm, steady, patient, concise' },
  },
  {
    id: 'lumi',
    name: 'Lumi',
    tagline: 'صاحبة النجوم، بتحب تطير.',
    description: 'A starry sprite with an imaginative, upbeat presence.',
    accent: '#9D7CD5',
    renderer: { kind: 'svg-recipe', species: 'sprite', motionScale: 0.4, canFly: true },
    persona: { style: 'imaginative, upbeat, curious, warm, concise' },
  },
  {
    id: 'naseem',
    name: 'Naseem',
    tagline: 'خفة وهدوء وأجنحة نعناع.',
    description: 'A soft mint-winged sprite with a calm, airy conversational style.',
    accent: '#75B9AC',
    renderer: {
      kind: 'svg-recipe',
      species: 'sprite',
      motionScale: 0.35,
      canFly: true,
      recipe: {
        fur: '#E4F3EB',
        cream: '#FFFBEB',
        accent: '#6FBBAC',
        eyes: '#418E8B',
      },
    },
    persona: { style: 'calm, light, thoughtful, gentle, concise' },
  },
] as const satisfies readonly CharacterDefinition[];

export const DEFAULT_CHARACTER_ID = 'otti';

export function getCharacterDefinition(id: string | null | undefined): CharacterDefinition {
  return characterRegistry.find((character) => character.id === id) ?? characterRegistry.find((character) => character.id === DEFAULT_CHARACTER_ID)!;
}
