import { speakingAssets } from './assets';
import type { SpeakingScenario } from './catalog';

export const A1_SPEAKING_PILOT_LESSONS: SpeakingScenario[] = [
  {
    id: 'a1-s1-l01',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'رد وخد دورك',
    descriptionAr: 'اتدرّب إنك ترد برد قصير مفهوم وتاخد دور كامل بدل كلمة واحدة أو سكوت.',
    learnerRoleAr: 'متكلم في محادثة قصيرة',
    aiRoleAr: 'شريك محادثة بيديك فرص واضحة للرد',
    goalAr: 'رد على أسئلة A1 مألوفة برد قصير كامل، وخلي دورك مفهوم من غير ما Otti يكمّل الجملة مكانك.',
    durationMinutes: 5,
    readiness: 'ready',
    readinessReasonAr: 'اللغة نفسها مألوفة؛ التدريب هنا على طريقة الرد وأخذ الدور.',
    usesAr: ['رد مفهوم مش كلمة واحدة', 'استنى السؤال يخلص وخد دورك', 'زود معلومة صغيرة لما تقدر'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['respond', 'maintain'],
    partnerBriefEn: 'This is a speaking-behaviour lesson, not a language lesson. Use already-available simple A1 personal language only as material. Give the learner several short, varied opportunities to answer familiar questions. Reward a clear complete turn, even if it is only one short sentence. If they answer with one isolated word when they can reasonably form a tiny utterance, ask one natural follow-up or recast once, then give another fresh opportunity. Do not teach the underlying vocabulary or grammar unless communication breaks down.',
    courseSourceAr: 'A1 shared ground • personal language already available',
    courseLessonIds: ['A1-U1-L01', 'A1-U1-L03', 'A1-U1-L04'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أساسيات المحادثة',
      lessonCode: 'S1-L01',
      position: 1,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01', 'U1-L03', 'U1-L04'],
    },
    skillFocusAr: 'Respond • Turn-taking',
    practiceStepsAr: ['فرصة رد بسيطة', 'نفس المهارة بسؤال مختلف', 'محادثة قصيرة من غير نموذج جاهز'],
    boundariesEn: ['The target is responding and taking a complete conversational turn, not teaching names, age, origin, jobs or grammar.', 'Use only familiar A1 material and keep questions short.', 'Do not require a fixed phrase or exact sentence if the learner communicates the meaning clearly.'],
    correctionFocusEn: ['Prioritise whether the learner actually responds and owns a complete turn.', 'Ignore non-target grammar errors when meaning is clear.', 'Intervene on language only when it blocks the response or makes the turn unclear.'],
    openingMoveEn: 'Start immediately with one very short familiar A1 question. Do not model an answer. After the learner responds, react naturally and create two or three fresh response opportunities using different simple content.',
  },
  {
    id: 'a1-s1-l02',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'ابدأ الحوار بنفسك',
    descriptionAr: 'اتدرّب إنك تعمل أول move بدل ما تستنى Otti يسألك كل مرة.',
    learnerRoleAr: 'الشخص اللي هيبدأ الكلام',
    aiRoleAr: 'شريك مستنيك تفتح المحادثة',
    goalAr: 'ابدأ محادثة A1 بسيطة بنفسك مرتين في سياقين مختلفين، من غير جملة نموذجية جاهزة.',
    durationMinutes: 5,
    readiness: 'ready',
    readinessReasonAr: 'تقدر تستخدم أي لغة A1 بسيطة عندك؛ النجاح هنا إنك أنت اللي تبدأ.',
    usesAr: ['ابدأ أول move', 'اختار افتتاحية مناسبة', 'سيب مساحة للطرف التاني يرد'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['initiate', 'respond'],
    partnerBriefEn: 'Train initiation as a speaking behaviour. The learner must make the first real conversational move. Do not begin with a greeting that steals the initiation. Give only a tiny coaching cue, then wait for the learner to start. After one short exchange, reset with a slightly different simple social context and let the learner initiate again. Use any simple A1 language they already have; do not turn this into a greeting-vocabulary lesson.',
    courseSourceAr: 'A1 shared ground • greetings + personal language',
    courseLessonIds: ['A1-U1-L01', 'A1-U1-L03', 'A1-U1-L04'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أساسيات المحادثة',
      lessonCode: 'S1-L02',
      position: 2,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01', 'U1-L03', 'U1-L04'],
    },
    skillFocusAr: 'Initiate',
    practiceStepsAr: ['Otti يديك cue صغير وإنت تبدأ', 'تبادل قصير', 'سياق جديد وإنت تبدأ تاني'],
    boundariesEn: ['Do not assess whether the learner used one preferred greeting formula.', 'Do not ask a question before the learner has had a chance to initiate.', 'Language accuracy is secondary to making an appropriate first move.'],
    correctionFocusEn: ['Did the learner initiate without being given the full wording?', 'Was the opening understandable and socially plausible?', 'Do not correct small grammar issues if the opening works.'],
    openingMoveEn: 'Say only a brief Egyptian-Arabic coaching cue equivalent to “إنت ابدأ الكلام” and then give the learner the turn. Do not greet them first and do not supply an English model sentence.',
  },
  {
    id: 'a1-s1-l03',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'خلّي الكلام يكمل',
    descriptionAr: 'بعد ما ترد، ما تقفلش الحوار فورًا: اعمل follow-up بسيط أو رجّع السؤال للطرف التاني.',
    learnerRoleAr: 'شريك مسؤول عن استمرار الحوار',
    aiRoleAr: 'شريك محادثة بيدي معلومات تقدر تبني عليها',
    goalAr: 'بعد ردك، اعمل move إضافي بسيط يحافظ على الحوار في أكتر من تبادل.',
    durationMinutes: 6,
    readiness: 'ready',
    readinessReasonAr: 'هتستخدم لغة A1 مألوفة، لكن التركيز على follow-up واستمرار التبادل.',
    usesAr: ['رد + move تاني', 'And you? لما يكون طبيعي', 'سؤال متابعة بسيط من معنى الكلام'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['follow-up', 'maintain', 'respond'],
    partnerBriefEn: 'Train follow-up and maintenance. Use simple familiar personal topics only as conversation material. Give the learner information that creates an obvious reason to continue. Do not keep rescuing the conversation with your own questions: after the learner answers, leave a natural opening for them to ask or return something. If they stop, wait briefly, then give a very small cue rather than the exact follow-up wording. Vary the topic once so they transfer the behaviour.',
    courseSourceAr: 'A1 shared ground • personal details + work/study + place language',
    courseLessonIds: ['A1-U1-L01', 'A1-U1-L02', 'A1-U1-L03', 'A1-U1-L04'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أساسيات المحادثة',
      lessonCode: 'S1-L03',
      position: 3,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01', 'U1-L02', 'U1-L03', 'U1-L04'],
    },
    skillFocusAr: 'Follow-up • Maintain',
    practiceStepsAr: ['رد على Otti', 'زود سؤال أو رجّع الدور', 'جرّب نفس المهارة في موضوع مختلف'],
    boundariesEn: ['The target is keeping the exchange alive, not covering personal-information content.', 'A very simple follow-up is enough at A1.', 'Do not force And you? when another simple question is more natural.'],
    correctionFocusEn: ['Did the learner create a next conversational move?', 'Did the follow-up connect to the exchange?', 'Do not open grammar teaching because of a non-target error.'],
    openingMoveEn: 'Begin a tiny familiar exchange and answer the learner with one simple fact that gives them something to follow up on. Avoid immediately asking another question after every learner response; leave room for the learner to maintain the conversation.',
  },
  {
    id: 'a1-s1-l04',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'مش فاهم — وضّح',
    descriptionAr: 'لما معلومة تضيع منك، اطلب repetition أو spelling أو clarification بدل ما تخمّن أو تسكت.',
    learnerRoleAr: 'متكلم محتاج يحافظ على الفهم',
    aiRoleAr: 'شريك محادثة هيخلق فرصة توضيح حقيقية',
    goalAr: 'استخدم clarification move مناسب مرتين على الأقل لما جزء مهم من الكلام يكون غير واضح.',
    durationMinutes: 6,
    readiness: 'ready',
    readinessReasonAr: 'لغة التوضيح موجودة في A1؛ هنا بنتدرب على استخدامها في اللحظة الصح.',
    usesAr: ['اطلب إعادة الكلام', 'اطلب spelling لما ينفع', 'أكد إنك فهمت التفصيلة صح'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['clarify', 'maintain'],
    partnerBriefEn: 'Create genuine, fair clarification opportunities inside A1. Use an invented name, email fragment, place name or simple detail that is easy enough to understand after repetition but not automatically obvious the first time. Do not pretend the audio failed and do not use advanced vocabulary. Let the learner choose whether to ask for repetition, spelling or confirmation. After clarification, continue the conversation so the repair has a purpose.',
    courseSourceAr: 'A1 shared ground • clarification/contact language',
    courseLessonIds: ['A1-U1-L05', 'A1-U1-L01', 'A1-U1-L03'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أساسيات المحادثة',
      lessonCode: 'S1-L04',
      position: 4,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L05', 'U1-L01', 'U1-L03'],
    },
    skillFocusAr: 'Clarify',
    practiceStepsAr: ['معلومة فيها تفصيلة مش واضحة', 'إنت تختار طريقة التوضيح', 'أكد التفصيلة وكمل الحوار'],
    boundariesEn: ['Do not teach a list of clarification phrases before the learner attempts the behaviour.', 'Never request real contact information; all details must be fictional.', 'The ambiguity must be genuine but fair, not caused by intentionally bad audio or advanced language.'],
    correctionFocusEn: ['Did the learner signal non-understanding instead of guessing?', 'Was the clarification move understandable?', 'If meaning is clear, accept different simple wording instead of demanding one phrase.'],
    openingMoveEn: 'Start a short A1 exchange and soon introduce one fictional detail that is naturally worth clarifying. Give the learner time to ask for clarification before you repeat or spell it on your own.',
  },
  {
    id: 'a1-s1-l05',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'صلّح الحوار وكمل',
    descriptionAr: 'لو Otti فهمك غلط أو التقط تفصيلة غلط، صحّح المعنى وكمّل بدل ما المحادثة تقع.',
    learnerRoleAr: 'متكلم مسؤول عن إصلاح سوء فهم بسيط',
    aiRoleAr: 'شريك هيعمل misunderstanding صغير ومقصود',
    goalAr: 'اكتشف سوء فهم بسيط، صحّح المعلومة أو أعد صياغتها، وبعدها كمّل الحوار طبيعي.',
    durationMinutes: 7,
    readiness: 'ready',
    readinessReasonAr: 'المحتوى اللغوي بسيط؛ التحدي هو repair الحقيقي أثناء التفاعل.',
    usesAr: ['صحّح تفصيلة غلط', 'قول قصدك تاني بطريقة أبسط', 'ارجع للحوار بعد الإصلاح'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['repair', 'maintain', 'respond'],
    partnerBriefEn: 'Train conversational repair, not grammar correction. First establish one simple learner-provided detail. Later misunderstand exactly one key detail in a plausible way, for example the city, job, number or name. Do not announce that this is a test. Give the learner room to notice and correct you. If they repair successfully, acknowledge it and continue. Later create one second lighter opportunity where the learner can rephrase if needed. Never manufacture repeated confusion just to make the learner fail.',
    courseSourceAr: 'A1 shared ground • prior personal language + clarification resources',
    courseLessonIds: ['A1-U1-L01', 'A1-U1-L02', 'A1-U1-L03', 'A1-U1-L04', 'A1-U1-L05'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أساسيات المحادثة',
      lessonCode: 'S1-L05',
      position: 5,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01', 'U1-L02', 'U1-L03', 'U1-L04', 'U1-L05'],
    },
    skillFocusAr: 'Repair • Maintain',
    practiceStepsAr: ['Otti يلقط تفصيلة غلط', 'إنت تصلح المعنى', 'تكمل الحوار بعد الإصلاح'],
    boundariesEn: ['The misunderstanding must be about meaning, not a trap about grammar terminology.', 'One successful repair is more important than perfect English.', 'Do not correct the learner while they are trying to repair unless the meaning is still unclear.'],
    correctionFocusEn: ['Did the learner notice or respond to the misunderstanding?', 'Did they correct or reformulate the intended meaning?', 'Did they return to the conversation after the repair?'],
    openingMoveEn: 'Begin a normal short A1 conversation and collect one simple detail from the learner. Continue naturally, then later misremember or misunderstand that one detail once so the learner has a real repair opportunity.',
  },
];

export function a1SpeakingPilotLessonById(id?: string) {
  return A1_SPEAKING_PILOT_LESSONS.find((lesson) => lesson.id === id);
}

export function nextA1SpeakingPilotLesson(id?: string) {
  const index = A1_SPEAKING_PILOT_LESSONS.findIndex((lesson) => lesson.id === id);
  return index >= 0 ? A1_SPEAKING_PILOT_LESSONS[index + 1] : undefined;
}
