import { speakingAssets } from './assets';
import type { SpeakingScenario } from './catalog';

export const A1_SPEAKING_PILOT_LESSONS: SpeakingScenario[] = [
  {
    id: 'a1-s1-l01',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'Hello, I’m…',
    descriptionAr: 'ابدأ تعارف بسيط: سلّم، قول اسمك، اسأل عن الاسم، ورد على سؤال بسيط عن حالك.',
    learnerRoleAr: 'نفسك',
    aiRoleAr: 'شخص بتقابله لأول مرة',
    goalAr: 'ابدأ وأنهِ تعارف قصير باستخدام التحية والاسم والسؤال عن الحال.',
    durationMinutes: 4,
    readiness: 'ready',
    readinessReasonAr: 'ده أول درس في مسار Speaking A1، والمستوى مضبوط تلقائيًا على A1.',
    usesAr: ['Hello / Hi', 'I’m… / My name is…', 'What’s your name?', 'How are you?', 'Thanks'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['initiate', 'respond', 'maintain', 'close'],
    partnerBriefEn: 'You are meeting the learner for the first time in a friendly ordinary setting. Keep the exchange tiny and natural: greeting, names, one basic wellbeing exchange, then a natural close. Do not add extra biography questions yet.',
    courseSourceAr: 'A1 • الوحدة 1 • الدرس 1',
    courseLessonIds: ['A1-U1-L01'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أول تعارف وبيانات شخصية',
      lessonCode: 'S1-L01',
      position: 1,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01'],
    },
    targetLanguageEn: ['Hello / Hi', 'Good morning', "I'm …", 'My name is …', "What's your name?", 'How are you?', 'simple wellbeing answers', 'Thank you / Thanks'],
    boundariesEn: ['Use only minimal first- and second-person forms of be needed for the exchange.', 'Do not introduce broader reaction/news language; that belongs to a later lesson.', 'Do not turn the lesson into a grammar explanation.'],
    correctionFocusEn: ['name introduction with I am / I’m or My name is', "What's your name?", 'basic intelligible wellbeing response'],
    openingMoveEn: 'Start with one simple A1 greeting only. Give the learner space to greet back and introduce themselves. Do not provide a model answer before they try.',
  },
  {
    id: 'a1-s1-l02',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'How old are you?',
    descriptionAr: 'اتدرّب على سؤال العمر وقوله بأرقام بسيطة داخل تعارف قصير.',
    learnerRoleAr: 'نفسك أو شخصية خيالية',
    aiRoleAr: 'زميل في نشاط تعارف بسيط',
    goalAr: 'اسأل عن العمر وقل عمرًا بسيطًا بوضوح. ينفع تستخدم عمرًا خياليًا.',
    durationMinutes: 4,
    readiness: 'ready',
    readinessReasonAr: 'الدرس يركز على عمر وأرقام A1 الوظيفية فقط، من غير أرقام كبيرة.',
    usesAr: ['How old are you?', 'I’m … years old', 'أرقام بسيطة للعمر'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['respond', 'follow-up'],
    partnerBriefEn: 'You are in a simple language-club introduction activity. Use age only as the target information. The learner may use a fictional age. Keep number language small and practical and do not drift into dates, prices, phone numbers or large numbers.',
    courseSourceAr: 'A1 • الوحدة 1 • الدرس 2',
    courseLessonIds: ['A1-U1-L02'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أول تعارف وبيانات شخصية',
      lessonCode: 'S1-L02',
      position: 2,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L02'],
    },
    targetLanguageEn: ['How old are you?', '… years old', 'basic functional number patterns for age'],
    boundariesEn: ['Do not require large-number language.', 'Do not expand into dates, contact numbers, prices or quantities.', 'Never pressure the learner to disclose a real age; fictional information is fully acceptable.'],
    correctionFocusEn: ['intelligible age number', 'How old are you?', 'natural age answer with be / years old'],
    openingMoveEn: 'Open with a very short friendly line that makes an age exchange plausible. Ask one age question, then let the learner ask you too. Never demand a real age.',
  },
  {
    id: 'a1-s1-l03',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'Where are you from?',
    descriptionAr: 'قول أنت منين وعايش فين، واسأل الطرف التاني نفس النوع من الأسئلة.',
    learnerRoleAr: 'نفسك أو شخصية خيالية',
    aiRoleAr: 'شخص جديد في لقاء اجتماعي بسيط',
    goalAr: 'اسأل وقل بلد/مدينة الأصل ومكان السكن بجمل قصيرة.',
    durationMinutes: 5,
    readiness: 'ready',
    readinessReasonAr: 'المطلوب origin وresidence فقط بلغة A1 قصيرة.',
    usesAr: ['Where are you from?', 'I’m from…', 'I live in…'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'You are meeting the learner socially. Exchange only simple origin and residence information. Contribute your own fictional city/country so the exchange feels two-sided. Keep follow-ups very short and inside the target.',
    courseSourceAr: 'A1 • الوحدة 1 • الدرس 3',
    courseLessonIds: ['A1-U1-L03'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أول تعارف وبيانات شخصية',
      lessonCode: 'S1-L03',
      position: 3,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L03'],
    },
    targetLanguageEn: ['Where are you from?', "I'm from …", 'I live in …', 'come from …'],
    boundariesEn: ['Keep questions and answers short; do not demand extended descriptions of hometowns or countries.', 'Do not require nationality grammar or advanced place description unless the learner volunteers it.', 'Fictional location information is acceptable.'],
    correctionFocusEn: ["I'm from …", 'I live in …', 'Where are you from?'],
    openingMoveEn: 'Start as a new acquaintance with one short location-related question after a greeting. Let the learner ask you a similar question before closing.',
  },
  {
    id: 'a1-s1-l04',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'What do you do?',
    descriptionAr: 'اتكلم عن شغل أو دراسة في جملة بسيطة واسأل سؤال متابعة واحد.',
    learnerRoleAr: 'نفسك أو شخصية خيالية',
    aiRoleAr: 'شخص بتتعرف عليه',
    goalAr: 'قل معلومة واحدة عن الشغل/الدراسة واسأل عن شغل أو دراسة الطرف التاني.',
    durationMinutes: 5,
    readiness: 'ready',
    readinessReasonAr: 'الدرس يستخدم core صغير من job/student language، مش قائمة وظائف للحفظ.',
    usesAr: ['What do you do?', 'I’m a…', 'I work as…', 'I study…'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'You are a new acquaintance. Exchange one simple work or study fact each. Use a small familiar job/student vocabulary core and do not quiz the learner on job names. Give one easy follow-up opportunity.',
    courseSourceAr: 'A1 • الوحدة 1 • الدرس 4',
    courseLessonIds: ['A1-U1-L04'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أول تعارف وبيانات شخصية',
      lessonCode: 'S1-L04',
      position: 4,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L04'],
    },
    targetLanguageEn: ["I'm a …", 'I work as …', 'I work for …', 'basic job / student language', 'What do you do?'],
    boundariesEn: ['Use a small active job/study vocabulary core; do not demand recall of a broad job list.', 'One simple fact plus one related question is enough.', 'Do not drift into detailed workplace, career history or responsibilities.'],
    correctionFocusEn: ["I'm a …", 'I work as … / I study …', 'basic related question'],
    openingMoveEn: 'Begin with a short social transition into work/study. Ask only one simple target question and contribute one simple fictional fact about yourself.',
  },
  {
    id: 'a1-s1-l05',
    worldId: 'curriculum',
    groupId: 'a1-unit-1',
    titleAr: 'Contact details & clarification',
    descriptionAr: 'بدّل بيانات تواصل خيالية، واطلب spelling أو repetition لما معلومة تكون مش واضحة.',
    learnerRoleAr: 'شخص بيسجل بيانات تواصل خيالية',
    aiRoleAr: 'زميل بيديك بيانات تواصل خيالية',
    goalAr: 'تبادل معلومة تواصل خيالية واحدة واعمل clarification حقيقي لو جزء منها مش واضح.',
    durationMinutes: 6,
    readiness: 'ready',
    readinessReasonAr: 'التركيز على contact + repair، مش درس modal عام.',
    usesAr: ['phone / email / address', 'How do you spell that?', 'Can you say that again?', 'تأكيد معلومة'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'practice',
    interactionFocus: ['respond', 'clarify', 'repair'],
    partnerBriefEn: 'Run a tiny information-gap using invented contact details only. Give one fictional email, phone fragment or address detail with one naturally hard-to-catch element so the learner has a genuine reason to ask for spelling, repetition or confirmation. Never request or store the learner’s real contact information.',
    courseSourceAr: 'A1 • الوحدة 1 • الدرس 5',
    courseLessonIds: ['A1-U1-L05'],
    curriculum: {
      level: 'A1',
      unit: 1,
      unitTitleAr: 'أول تعارف وبيانات شخصية',
      lessonCode: 'S1-L05',
      position: 5,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L05'],
    },
    targetLanguageEn: ['basic phone / email / address detail', 'How do you spell that?', 'Can you say that again?', 'Can you repeat that?', 'simple confirmation of one detail'],
    boundariesEn: ['Use invented contact details only; never ask for real phone numbers, email addresses or home addresses.', 'This is a repair/contact task, not a generic can/modal grammar lesson.', 'Create a genuine information gap instead of pretending audio was unclear.'],
    correctionFocusEn: ['clarification request', 'spelling request', 'confirmation of one contact detail'],
    openingMoveEn: 'Start with a simple reason to exchange one fictional contact detail. Give a made-up detail and include one element that the learner may reasonably need to clarify. Do not ask for real personal data.',
  },
];

export function a1SpeakingPilotLessonById(id?: string) {
  return A1_SPEAKING_PILOT_LESSONS.find((lesson) => lesson.id === id);
}

export function nextA1SpeakingPilotLesson(id?: string) {
  const index = A1_SPEAKING_PILOT_LESSONS.findIndex((lesson) => lesson.id === id);
  return index >= 0 ? A1_SPEAKING_PILOT_LESSONS[index + 1] : undefined;
}
