import { speakingAssets } from './assets';
import type { SpeakingScenario } from './catalog';

export const LEARN_V2_B1_SPEAKING_MISSIONS: SpeakingScenario[] = [
  {
    id: 'learn-v2-b1-u1-l01',
    worldId: 'curriculum',
    groupId: 'learn-v2-b1-unit-1',
    titleAr: 'Catch up من غير سكريبت',
    descriptionAr: 'ادخل في محادثة مألوفة من opening غير متوقع وخلي الخطوة الجاية تطلع من كلام الطرف التاني.',
    learnerRoleAr: 'نفسك',
    aiRoleAr: 'شخص تعرفه وبتقابله بعد فترة',
    goalAr: 'ادخل في الكلام من غير نموذج جاهز، تفاعل مع المعنى، امسك تفصيلة، واخلق next move طبيعي أكتر من مرة.',
    durationMinutes: 7,
    readiness: 'ready',
    readinessReasonAr: 'الدرس جهّزك بالـphrases والـlistening قبل المهمة، لكن المحادثة نفسها مش scripted.',
    usesAr: ['ادخل من غير سكريبت', 'رد فعل مناسب', 'follow-up من كلام الشخص', 'حافظ على الحوار', 'hear of / get on with / too bad لو السياق مناسب'],
    image: speakingAssets.meetingPeople,
    liveCharacterImage: speakingAssets.ottiHero,
    modeId: 'just-chat',
    applicationType: 'embedded',
    interactionFocus: ['initiate', 'respond', 'follow-up', 'maintain', 'develop'],
    partnerBriefEn: 'You are a familiar acquaintance the learner has not seen for a while. Open with one unpredictable but familiar update, not a textbook greeting script and not a question list. Have a genuine two-sided catch-up. Offer details the learner can react to and follow up on. Let topics develop from what each person actually says. The lesson phrases Have you heard of…, get on with somebody and Too bad are available resources; create believable opportunities for them if the conversation naturally allows, but never demand all of them or feed them as answers. The words competitor, entertainment, photography, rugby and talented are receptive ground, not required productive targets.',
    courseSourceAr: 'Learn V2 • B1 U1-L01',
    courseLessonIds: ['B1-U1-L01'],
    curriculum: {
      level: 'B1',
      unit: 1,
      unitTitleAr: 'From Routine Exchange to Independent Conversation',
      lessonCode: 'B1-U1-L01',
      position: 1,
      totalInUnit: 7,
      sourceLessonIds: ['U1-L01'],
    },
    skillFocusAr: 'Unprepared familiar conversation • next move',
    practiceStepsAr: ['اسمع opening غير متوقعة', 'React → Pick → Continue بشكل طبيعي', 'المساعدة متاحة من غير ما تعتبر إجابة مستقلة'],
    targetLanguageEn: [
      'enter an unprepared familiar conversation and establish a topic',
      'react to what the partner actually said and create a relevant next move',
      'Have you heard of … ? where context genuinely fits',
      'get on with somebody where context genuinely fits',
      'Too bad as a sympathetic reaction where context genuinely fits',
      'receptive support only: competitor, entertainment, photography, rugby, talented',
    ],
    boundariesEn: [
      'This is B1 U1-L01 only. Do not import U1-L02 turn-management targets or later repair/interview requirements as hidden success conditions.',
      'The three source phrases are useful productive resources, not a checklist that all must appear in one conversation.',
      'The five source words are receptive support. Never require the learner to force them into speech.',
      'A relevant spontaneous next move matters more than perfect grammar.',
    ],
    correctionFocusEn: [
      'whether the learner reacts to the actual meaning rather than giving a generic canned response',
      'whether follow-up or added information grows from a detail in the partner turn',
      'whether the learner helps create the next move instead of waiting for an interview question',
      'light intelligibility support only; do not chase accent perfection',
    ],
    openingMoveEn: 'Open with one short, believable personal update that is familiar but unpredictable, for example “You won’t believe it — I started something new last month.” Do not explain the task and do not immediately ask the learner a question. Give them room to react and create the next move.',
    learnMission: true,
    hideEvidenceProgress: true,
    returnPath: '/learn/pilot/b1-u1-l01',
  },
];
