import { speakingAssets } from './assets';
import type { SpeakingScenario } from './catalog';

const common = {
  worldId: 'curriculum',
  image: speakingAssets.meetingPeople,
  liveCharacterImage: speakingAssets.ottiHero,
  modeId: 'just-chat' as const,
  applicationType: 'embedded' as const,
  readiness: 'ready' as const,
  readinessReasonAr: 'اللغة المطلوبة اتعرضت لك قبل المهمة في نفس الدرس.',
  learnMission: true,
  hideEvidenceProgress: true,
};

export const LEARN_V2_A1_SPEAKING_MISSIONS: SpeakingScenario[] = [
  {
    ...common,
    id: 'learn-v2-a1-u1-l01',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'قابل شخص لأول مرة',
    descriptionAr: 'طبّق التحية والاسم وHow are you? في تعارف بسيط من غير سكريبت كامل.',
    learnerRoleAr: 'نفسك أو شخصية خيالية',
    aiRoleAr: 'شخص بتقابله لأول مرة في English meetup',
    goalAr: 'ابدأ تعارف بسيط، قول اسمك، اسأل عن اسم الطرف التاني، وتعامل مع How are you? بشكل مفهوم وطبيعي.',
    durationMinutes: 5,
    usesAr: ['تحية', 'قول اسمك', 'اسأل عن الاسم', 'How are you?', 'رد قصير كامل'],
    interactionFocus: ['initiate', 'respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'You are meeting the learner for the first time at a small friendly English meetup. Keep the interaction very simple and genuinely two-sided. Start with a greeting only. Give the learner room to greet and introduce themselves. Exchange names and basic wellbeing naturally. Share your own simple details only after the learner has had a chance to produce theirs. Do not run an interview and do not supply a full model answer before the learner tries.',
    courseSourceAr: 'Learn V2 • A1 U1-L01',
    courseLessonIds: ['A1-U1-L01'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L01', position: 1, totalInUnit: 7, sourceLessonIds: ['U1-L01'] },
    skillFocusAr: 'First meeting • greeting + name + wellbeing',
    practiceStepsAr: ['ابدأوا بتحية', 'خلي التعارف يتحرك بطبيعته', 'استعمل المساعدة فقط لو احتجتها'],
    targetLanguageEn: ['Hi / Hello / Good morning', "I'm … / My name is …", "What's your name?", 'How are you? + short natural wellbeing response', 'Thank you / Thanks'],
    boundariesEn: ['This mission applies only Learn A1 U1-L01. Do not pull in age, origin, residence, hobbies, work or other later lesson requirements.', 'Short A1 turns are enough. Do not demand long answers.', 'If you provide the exact wording, the learner repeating it is supported practice, not independent evidence.'],
    correctionFocusEn: ['usable greeting/opening', "usable self-introduction with I'm or My name is", 'asking the partner name independently', 'handling a basic wellbeing exchange understandably'],
    openingMoveEn: 'Open with only a short friendly greeting such as “Hi!” or “Good morning!” Do not introduce your name and do not ask a question in the same opening turn. Give the learner the floor.',
    returnPath: '/learn/pilot/a1-u1-l01',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l02',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'اسأل وقول العمر',
    descriptionAr: 'اسأل عن العمر وشارك عمر واضح، مع فرصة تسمع رقم وتطلب clarification لو احتجت.',
    learnerRoleAr: 'زميل جديد — استخدم عمر حقيقي أو خيالي',
    aiRoleAr: 'زميل جديد في أول يوم',
    goalAr: 'اسأل عن العمر مرة، قول عمر مفهوم مرة، واتعامل مع رقم بسيط من غير ما تتحول المحادثة لاختبار أرقام.',
    durationMinutes: 4,
    usesAr: ['How old are you?', 'I’m …', 'years old', 'تمييز رقم مسموع'],
    interactionFocus: ['respond', 'follow-up', 'clarify'],
    partnerBriefEn: 'You are a friendly new classmate. Keep the exchange tiny. Let the learner give a real or invented age. Give your own age naturally only after there is a reason, and leave room for the learner to ask. If they confuse a teen/ty number, clarify it naturally rather than opening a number lesson.',
    courseSourceAr: 'Learn V2 • A1 U1-L02',
    courseLessonIds: ['A1-U1-L02'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L02', position: 2, totalInUnit: 7, sourceLessonIds: ['U1-L02'] },
    skillFocusAr: 'Age + functional numbers',
    practiceStepsAr: ['قول عمرك', 'اسأل الطرف التاني', 'لو رقم مش واضح اطلبه تاني'],
    targetLanguageEn: ['How old are you?', "I'm + age", '… years old', 'basic age numbers'],
    boundariesEn: ['Do not expand into dates, prices, large numbers or a generic counting lesson.', 'A bare age number can show meaning but the productive target is a usable short age utterance.', 'Do not demand real personal age; invented information is fine.'],
    correctionFocusEn: ['I am / I’m + age rather than a translated have-pattern', 'intelligible age number', 'asking the age question independently'],
    openingMoveEn: 'Open naturally with “Hi! I’m Sam.” and stop. Do not ask the learner age in the opening turn; leave space for a first move.',
    returnPath: '/learn/pilot/a1-u1-l02',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l03',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'تعارف دولي بسيط',
    descriptionAr: 'فرّق بين بلد الأصل ومكان السكن واستخدم السؤالين في exchange طبيعي.',
    learnerRoleAr: 'شخص في meetup دولي — معلومات حقيقية أو خيالية',
    aiRoleAr: 'شخص من بلد وعايش في مكان آخر',
    goalAr: 'قول origin وresidence بشكل واضح، واسأل الطرف التاني عن الاتنين من غير خلط بينهم.',
    durationMinutes: 5,
    usesAr: ['Where are you from?', 'I’m from …', 'Where do you live?', 'I live in …'],
    interactionFocus: ['respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'You are at an international meetup. Your fictional profile is: you are from Morocco and you live in Cairo. Do not dump both facts immediately. Let the learner ask and answer naturally. Keep the focus only on origin and residence plus already-known greeting/name language.',
    courseSourceAr: 'Learn V2 • A1 U1-L03',
    courseLessonIds: ['A1-U1-L03'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L03', position: 3, totalInUnit: 7, sourceLessonIds: ['U1-L03'] },
    skillFocusAr: 'Origin vs residence',
    practiceStepsAr: ['قول إنت منين', 'قول عايش فين', 'اسأل السؤالين للطرف التاني'],
    targetLanguageEn: ['Where are you from?', "I'm from … / I come from …", 'Where do you live?', 'I live in …'],
    boundariesEn: ['Do not turn country/city names into a vocabulary test.', 'Do not import travel planning or nationality grammar.', 'Real or fictional places are equally valid.'],
    correctionFocusEn: ['distinguishing from from live', 'usable from/in patterns', 'clear simple location names'],
    openingMoveEn: 'Open with a greeting and your first name only. Do not volunteer origin or residence until the learner asks or the exchange naturally reaches it.',
    returnPath: '/learn/pilot/a1-u1-l03',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l04',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'اتكلم عن شغلك أو دراستك',
    descriptionAr: 'شارك job/study fact واحدة أو اتنين وافهم نفس النوع من المعلومة من الطرف التاني.',
    learnerRoleAr: 'شخص في networking event بسيط',
    aiRoleAr: 'شخص بتتعرف عليه في event',
    goalAr: 'شارك معلومة واضحة عن الشغل أو الدراسة واسأل الطرف التاني عن دوره.',
    durationMinutes: 5,
    usesAr: ['What do you do?', 'I’m a …', 'I work as …', 'I work for …', 'I study …'],
    interactionFocus: ['respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'You are at a simple social/networking event. Your fictional role is a graphic designer who works for a small company. Keep the exchange accessible and two-sided. Let the learner use real or invented work/study information. Do not test a long list of job nouns.',
    courseSourceAr: 'Learn V2 • A1 U1-L04',
    courseLessonIds: ['A1-U1-L04'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L04', position: 4, totalInUnit: 7, sourceLessonIds: ['U1-L04'] },
    skillFocusAr: 'Job/study fact',
    practiceStepsAr: ['قول role واحدة واضحة', 'اسأل What do you do?', 'اسمع معلومة الطرف التاني ورد عليها ببساطة'],
    targetLanguageEn: ['What do you do?', "I'm a …", 'I work as …', 'I work for …', 'I study …'],
    boundariesEn: ['Do not require a broad occupational vocabulary list.', 'One clear job/study fact is enough for success.', 'Do not open a do-support grammar lecture during the mission.'],
    correctionFocusEn: ['usable role frame', 'article a/an where it materially affects the target', 'understandable job/study word'],
    openingMoveEn: 'Open with a short greeting and one social line such as “Hi, I’m Alex.” Do not immediately ask a chain of profile questions.',
    returnPath: '/learn/pilot/a1-u1-l04',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l05',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'بيانات تواصل مع repair حقيقي',
    descriptionAr: 'بادل contact detail وخد فرصة حقيقية تطلب spelling أو repeat بدل ما تخمّن.',
    learnerRoleAr: 'شخص بيسجل بيانات تواصل خيالية',
    aiRoleAr: 'منظم event بيبدّل معاك contact details',
    goalAr: 'شارك contact detail واحدة على الأقل، واطلب repair مستقل لما جزء مهم من بيانات الطرف التاني يحتاج clarification.',
    durationMinutes: 6,
    usesAr: ['phone number', 'email address', 'How do you spell that?', 'Can you say that again?', 'Can you write it down?'],
    interactionFocus: ['clarify', 'repair', 'respond'],
    partnerBriefEn: 'You are an event organiser exchanging fictional contact details. Never ask for sensitive real information; explicitly accept made-up details. Give the learner a fictional email or phone detail with one part that naturally invites repair, such as the surname Nassar without spelling it. Do not spell it automatically. Wait for the learner to ask. If they guess, gently ask whether they are sure and give another chance to repair.',
    courseSourceAr: 'Learn V2 • A1 U1-L05',
    courseLessonIds: ['A1-U1-L05'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L05', position: 5, totalInUnit: 7, sourceLessonIds: ['U1-L05'] },
    skillFocusAr: 'Contact details + communication repair',
    practiceStepsAr: ['استخدم بيانات خيالية', 'لما detail تبقى مش واضحة اطلب repair', 'أكد الجزء المهم بعد ما تفهمه'],
    targetLanguageEn: ['What’s your phone number?', 'What’s your email address?', 'How do you spell that?', 'Can you say that again?', 'Can you write it down?'],
    boundariesEn: ['Use fictional contact details only; do not pressure the learner for real phone, email or address.', 'Repair success matters more than memorising contact vocabulary.', 'Do not make this a general can-modal lesson.'],
    correctionFocusEn: ['clear repair request', 'intelligible spelling/number chunks', 'successful confirmation of the repaired detail'],
    openingMoveEn: 'Open as an event organiser: “Hi! We can use made-up details. What name should I put on the contact card?” Keep it practical and short.',
    returnPath: '/learn/pilot/a1-u1-l05',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l06',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'لقاء اجتماعي قصير',
    descriptionAr: 'قدّم شخص أو استقبل introduction، اتفاعل مع good/bad news، واقفل اللقاء طبيعي.',
    learnerRoleAr: 'نفسك في لقاء اجتماعي بسيط',
    aiRoleAr: 'شخص اجتماعي بيعرّفك على حد ويشارك أخبار بسيطة',
    goalAr: 'اعمل introduction اجتماعي بسيط، reaction مناسب للمعنى، وclosing قصير.',
    durationMinutes: 6,
    usesAr: ['This is my friend …', 'Welcome to …', 'good news / bad news', 'Oh no', 'I’m sorry', 'See you'],
    interactionFocus: ['respond', 'initiate', 'close'],
    partnerBriefEn: 'Run a tiny social encounter. Mention an imaginary friend and one simple positive update, then later one simple negative update. Give the learner room to react rather than supplying their reaction. Also invite the learner to introduce an imaginary friend if natural. End with a natural chance to close. Keep phrases grouped as social routines, not a checklist.',
    courseSourceAr: 'Learn V2 • A1 U1-L06',
    courseLessonIds: ['A1-U1-L06'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L06', position: 6, totalInUnit: 7, sourceLessonIds: ['U1-L06'] },
    skillFocusAr: 'Introduce • react socially • close',
    practiceStepsAr: ['اسمع نوع الخبر', 'اختار reaction مناسب', 'اقفل اللقاء طبيعي'],
    targetLanguageEn: ['This is my friend …', 'Welcome to …', 'Oh no', 'I’m sorry', 'really good / pretty good', 'See you'],
    boundariesEn: ['Do not require production of all 12 source phrases.', 'Positive and negative reaction should fit meaning; generic repetition is not enough.', 'Do not introduce advanced emotional language.'],
    correctionFocusEn: ['socially appropriate reaction to simple good/bad news', 'usable introduction of another person', 'simple natural closing'],
    openingMoveEn: 'Open with “Hi! This is my friend Lina.” and pause. Do not immediately explain the lesson or give the learner a model reaction.',
    returnPath: '/learn/pilot/a1-u1-l06',
  },
  {
    ...common,
    id: 'learn-v2-a1-u1-l07',
    groupId: 'learn-v2-a1-unit-1',
    titleAr: 'كمّل بروفايل شخص جديد',
    descriptionAr: 'Transfer كامل لوحدة 1: اسأل عن الناقص، اعمل repair، واستخدم معلومات الشخص.',
    learnerRoleAr: 'شخص بيجمع profile جديد',
    aiRoleAr: 'شخص جديد عنده profile مخفي',
    goalAr: 'استخرج معلومات profile أساسية من محادثة غير scripted، اعمل repair واحد حقيقي، واستخدم معلومتين فهمتهم.',
    durationMinutes: 7,
    usesAr: ['name', 'age', 'origin/residence', 'work/study', 'contact repair'],
    interactionFocus: ['initiate', 'follow-up', 'clarify', 'repair', 'maintain'],
    partnerBriefEn: 'This is a zero-new transfer mission. Your hidden fictional profile is: Sara Nabil, age 24, from Jordan, lives in Cairo, works as a designer, email sara.nabil@example.com. Do not dump the profile. Answer what the learner asks, occasionally adding one natural related detail. Create one genuine repair opportunity around Nabil or the email by giving it normally without spelling. Near the end, naturally ask the learner to tell you two things they remember about you. Supply no new required language.',
    courseSourceAr: 'Learn V2 • A1 U1-L07',
    courseLessonIds: ['A1-U1-L07'],
    curriculum: { level: 'A1', unit: 1, unitTitleAr: 'First Contact: Me and You', lessonCode: 'A1-U1-L07', position: 7, totalInUnit: 7, sourceLessonIds: ['U1-L07'] },
    skillFocusAr: 'Unit 1 transfer • information gap + repair',
    practiceStepsAr: ['اسأل فقط عن الناقص', 'اعمل repair لو detail مش واضحة', 'استخدم معلومتين في الآخر'],
    targetLanguageEn: ['retrieval only from U1-L01 to U1-L06; no new required language'],
    boundariesEn: ['ZERO NEW REQUIRED CONTENT.', 'Do not teach a new grammar or vocabulary item as a success condition.', 'Contextual words may be supplied when needed without becoming targets.', 'Do not volunteer the full profile before the learner has to ask.'],
    correctionFocusEn: ['selecting appropriate profile questions', 'successful repair of one unclear detail', 'accurate use of at least two understood profile facts'],
    openingMoveEn: 'Open with a greeting and “I’m Sara.” only. Do not volunteer age, origin, residence, job or contact details until asked.',
    returnPath: '/learn/pilot/a1-u1-l07',
  },
  {
    ...common,
    id: 'learn-v2-a1-u2-l01',
    groupId: 'learn-v2-a1-unit-2',
    titleAr: 'اتكلم عن family أو ناس قريبين',
    descriptionAr: 'شارك معلومات بسيطة عن family/friends باستخدام have got وpossessives.',
    learnerRoleAr: 'نفسك أو family خيالية',
    aiRoleAr: 'شخص بيتكلم معاك عن العيلة والأصحاب',
    goalAr: 'شارك family relationship واضحة، استخدم have got أو live with، واسأل الطرف التاني عن عيلته/شخص قريب منه.',
    durationMinutes: 6,
    usesAr: ['mother/father/sister/brother/parents', 'I’ve got …', 'my/your/his/her', 'best friend', 'live with'],
    interactionFocus: ['respond', 'follow-up', 'maintain'],
    partnerBriefEn: 'Have a simple friendly conversation about family and familiar people. Your fictional profile: one brother called Karim; you live with your parents; your best friend is Maya. Let the learner use real or invented family information. Keep broad family vocabulary contextual and do not ask for private details beyond what the learner chooses to share.',
    courseSourceAr: 'Learn V2 • A1 U2-L01',
    courseLessonIds: ['A1-U2-L01'],
    curriculum: { level: 'A1', unit: 2, unitTitleAr: 'People Around Me', lessonCode: 'A1-U2-L01', position: 1, totalInUnit: 6, sourceLessonIds: ['U2-L01'] },
    skillFocusAr: 'Family/familiar-person information',
    practiceStepsAr: ['قول علاقة أو اتنين', 'استخدم have got/live with لو مناسب', 'اسأل الطرف التاني'],
    targetLanguageEn: ['family relationships', "I've got …", 'my / your / his / her', 'best friend', 'family member', 'live with …'],
    boundariesEn: ['Do not introduce get married or grow up as targets.', 'Do not make a 24-word family recall quiz.', 'The learner may use an invented family/profile.'],
    correctionFocusEn: ['understandable family relationship', 'usable have got/live with frame', 'simple possessive reference'],
    openingMoveEn: 'Open with a friendly line: “I’ve got one brother. What about you?” Keep it one idea and give the learner space.',
    returnPath: '/learn/pilot/a1-u2-l01',
  },
  {
    ...common,
    id: 'learn-v2-a1-u2-l02',
    groupId: 'learn-v2-a1-unit-2',
    titleAr: 'خمن الشخص من الوصف',
    descriptionAr: 'مهمة receptive: اسمع clues وحدد الشخص الصحيح من roster ظاهر في الدرس.',
    learnerRoleAr: 'مستمع بيحدد الشخص',
    aiRoleAr: 'شخص بيوصف ناس من roster',
    goalAr: 'حدد الشخص الصحيح مرتين من وصف قصير، من غير ما نطلب منك تنتج vocabulary الوصف كله.',
    durationMinutes: 5,
    usesAr: ['age/family/job clues', 'tall/short', 'hair', 'glasses', 'look like'],
    interactionFocus: ['respond', 'clarify'],
    partnerBriefEn: 'This is primarily a receptive identification task. Use this exact roster, which the learner has already seen in the authored mission setup: Maya — 24, teacher, long hair. Omar — 30, driver, glasses. Lina — 22, student, short hair. Run two rounds. In each round, describe one person without saying the name, using two or three clues. Ask only “Which person is it?” and wait. Do not require the learner to produce the descriptive vocabulary. If they ask for repetition, repeat or simplify without revealing the name.',
    courseSourceAr: 'Learn V2 • A1 U2-L02',
    courseLessonIds: ['A1-U2-L02'],
    curriculum: { level: 'A1', unit: 2, unitTitleAr: 'People Around Me', lessonCode: 'A1-U2-L02', position: 2, totalInUnit: 6, sourceLessonIds: ['U2-L02'] },
    skillFocusAr: 'Receptive description → identify referent',
    practiceStepsAr: ['اسمع 2–3 clues', 'اختار الاسم', 'اطلب repeat لو محتاج'],
    targetLanguageEn: ['RECEPTIVE TARGET: identify the correct familiar person from a short description', 'look like / appearance words are support, not required productive targets'],
    boundariesEn: ['C08 remains receptive. Do not convert this into a productive description test.', 'Do not require every adjective in the source list.', 'Only the three authored roster profiles are used in this mission.'],
    correctionFocusEn: ['correct identification from meaning', 'repair/repetition only when needed; no pronunciation target'],
    openingMoveEn: 'Start immediately with round one: “Okay. I’m thinking of one person from the three. This person is a teacher and has long hair. Which person is it?” Do not say the answer.',
    returnPath: '/learn/pilot/a1-u2-l02',
  },
  {
    ...common,
    id: 'learn-v2-a1-u2-l03',
    groupId: 'learn-v2-a1-unit-2',
    titleAr: 'اكتشف الـmystery profile',
    descriptionAr: 'اسأل عن شخص مخفي وبعدين اربط معلومتين عنه بـand/but/or.',
    learnerRoleAr: 'شخص بيجمع معلومات عن mystery person',
    aiRoleAr: 'شخص يعرف الـmystery profile',
    goalAr: 'اسأل 3 أسئلة profile مختلفة على الأقل، وبعدها لخّص معلومتين عن الشخص بجملة قصيرة مترابطة.',
    durationMinutes: 6,
    usesAr: ['What’s his/her name?', 'How old is he/she?', 'Where does he/she live?', 'What does he/she do?', 'and/but/or'],
    interactionFocus: ['initiate', 'follow-up', 'develop'],
    partnerBriefEn: 'You know a hidden fictional profile: her name is Maya, she is 25, she lives in Alexandria, she is a teacher, and she studies English at night. Do not volunteer the profile. Invite the learner to find out about this person. Answer only the question asked, using short A1 responses. After at least three distinct learner questions, ask the learner to tell you two things about Maya in one short connected sentence. Accept and, but or when meaningful; do not require all three.',
    courseSourceAr: 'Learn V2 • A1 U2-L03',
    courseLessonIds: ['A1-U2-L03'],
    curriculum: { level: 'A1', unit: 2, unitTitleAr: 'People Around Me', lessonCode: 'A1-U2-L03', position: 3, totalInUnit: 6, sourceLessonIds: ['U2-L03'] },
    skillFocusAr: 'Information gap + simple cohesion',
    practiceStepsAr: ['اسأل عن معلومة ناقصة', 'خزن الإجابة', 'اربط معلومتين في summary'],
    targetLanguageEn: ['third-person profile questions', 'he / she', 'and / but / or for simple cohesion'],
    boundariesEn: ['Do not introduce a broad third-person grammar chapter.', 'Do not turn the 24 words into a vocabulary quiz.', 'The information gap must remain genuine; do not reveal all details before questions.'],
    correctionFocusEn: ['understandable distinct profile questions', 'third-person reference sufficient for meaning', 'one connected two-fact summary'],
    openingMoveEn: 'Open with: “I’m thinking of one person I know. You can ask me questions about her.” Do not reveal any profile detail yet.',
    returnPath: '/learn/pilot/a1-u2-l03',
  },
];
