import type { SupportedLocale } from '../i18n/locales';

export const practiceJourneyCopy = {
  en: {
    home: {
      eyebrow: 'Practice',
      title: 'Practice in a real situation',
      body: 'Choose your level and a situation. We design the mission, and Gemini Live keeps the conversation moving naturally with you.',
      featuresLabel: 'Practice features',
      features: ['Level-aware situations', 'Hints when you need them', 'No single memorized answer'],
      levelKicker: 'Practice level',
      levelTitle: 'What feels right for you now?',
      levelNote: 'The level is a filter that helps you find a useful challenge quickly, not a lock. You can explore any level whenever you want.',
      worldsKicker: 'Worlds',
      worldsTitle: 'What do you want to practise?',
      plannedForLevel: (count: string, level: string) => `${count} planned situations in ${level}`,
      worldCount: (count: string, level: string) => `${count} ${count === '1' ? 'situation' : 'situations'} in ${level}`,
      worldEmpty: (level: string) => `We will add ${level} situations here`,
      openKicker: 'Without a prepared mission',
      openTitle: 'Speak your own way',
      freeSpeakBody: 'An open conversation without a prepared blueprint or hints.',
      availableNow: 'Available now',
      customScenario: 'Custom scenario',
      customBody: 'Describe the situation you want to practise and have it generated for you.',
      comingSoon: 'Coming soon',
    },
    world: {
      back: 'All worlds',
      changeLevel: 'Change situation level',
      levelLabel: 'Level',
      situationsKicker: (level: string) => `${level} situations`,
      chooseMission: 'Choose a mission',
      plannedCount: (count: string) => `${count} planned`,
      libraryBuilding: 'The library is still being built',
      live: 'Available',
      planned: 'Coming soon',
      minutes: (minutes: string) => `About ${minutes} min`,
      start: 'Start',
      blueprint: 'Blueprint in progress',
      emptyTitle: 'This world is ready for content',
      emptyBody: (level: string) => `We will add ${level} missions here one by one from the new Practice library instead of filling it with situations just for the count.`,
      anotherWorld: 'Try another world',
      hintTitle: 'Hints belong to the mission itself',
      hintBody: 'When a mission is live, each beat has a clear intent, an Arabic meaning hint, useful English, and fuller help when needed.',
    },
    mission: {
      missingTitle: 'This mission is not ready yet',
      missingBody: 'Return to the library and choose an available situation.',
      backPractice: 'Back to Practice',
      backSituations: 'Back to situations',
      eyebrow: 'Practice mission',
      learnerRole: 'You',
      ottiRole: 'Otti',
      goal: 'Your goal',
      flowKicker: 'Designed conversation — not a script',
      flowTitle: 'What will you practise?',
      defaultBeat: 'Handle the situation in your own way',
      firstBeatHelp: 'You do not need to say one exact sentence',
      nextBeatHelp: 'What matters is expressing the meaning and keeping the situation moving naturally',
      hintTitle: 'The hint is smart and created for the moment',
      hintBody: 'If you get stuck and open Hint, Otti builds help from what actually happened in the conversation. The meaning, useful language, and a full example arrive together; then you reveal only the level of support you need.',
      minutes: (minutes: string) => `About ${minutes} min`,
      liveConversation: 'Live conversation',
      correction: 'Corrections only for genuine errors',
      start: 'Start mission',
    },
    complete: {
      missingTitle: 'Mission completed',
      eyebrow: 'Mission complete',
      title: 'You finished this situation',
      body: 'You reached the end of the situation successfully. That means you handled this mission; it is not a claim that all of the language is mastered.',
      arabicHints: 'Arabic hints',
      usefulWords: 'Useful words',
      fullHelp: 'Full help',
      usedHelpTitle: 'Used some help? Good — that is part of practice.',
      noHelpTitle: 'You finished this one without opening a hint.',
      usedHelpBody: 'If you want to build more independence, repeat the same situation and try using less help. There is no penalty for opening a hint.',
      noHelpBody: 'You can repeat it and see whether the same language comes out more easily, or return to the library for a new situation.',
      retry: 'Repeat mission',
      another: 'Another situation',
      backPractice: 'Back to Practice',
    },
  },
  ar: {
    home: {
      eyebrow: 'Practice',
      title: 'اتدرّب في موقف حقيقي',
      body: 'اختار مستواك والموقف. إحنا بنصمم المحادثة، وGemini Live بيخليها تتحرك طبيعي معاك.',
      featuresLabel: 'مميزات التدريب',
      features: ['مواقف حسب المستوى', 'Hints وقت ما تحتاج', 'مفيش إجابة واحدة محفوظة'],
      levelKicker: 'مستوى التدريب',
      levelTitle: 'إيه المناسب ليك دلوقتي؟',
      levelNote: 'المستوى فلتر يساعدك تلاقي المناسب بسرعة، مش قفل. تقدر تستكشف أي مستوى وقت ما تحب.',
      worldsKicker: 'العوالم',
      worldsTitle: 'عايز تتدرّب على إيه؟',
      plannedForLevel: (count: string, level: string) => `${count} مواقف مخطط لها في ${level}`,
      worldCount: (count: string, level: string) => `${count} ${count === '1' ? 'موقف' : 'مواقف'} في ${level}`,
      worldEmpty: (level: string) => `هنضيف مواقف ${level} هنا`,
      openKicker: 'من غير Mission جاهزة',
      openTitle: 'اتكلم بطريقتك',
      freeSpeakBody: 'محادثة مفتوحة من غير blueprint أو hints جاهزة.',
      availableNow: 'متاح دلوقتي',
      customScenario: 'Custom scenario',
      customBody: 'اكتب الموقف اللي عايز تتدرب عليه وخليه يتولد ليك.',
      comingSoon: 'قريبًا',
    },
    world: {
      back: 'كل العوالم',
      changeLevel: 'غيّر مستوى المواقف',
      levelLabel: 'المستوى',
      situationsKicker: (level: string) => `مواقف ${level}`,
      chooseMission: 'اختار Mission',
      plannedCount: (count: string) => `${count} مخطط لها`,
      libraryBuilding: 'المكتبة لسه بتتبني',
      live: 'متاح',
      planned: 'قريبًا',
      minutes: (minutes: string) => `حوالي ${minutes} دقائق`,
      start: 'ابدأ',
      blueprint: 'بنبني الـblueprint',
      emptyTitle: 'المكان جاهز للمحتوى',
      emptyBody: (level: string) => `هنضيف Missions ${level} هنا واحدة واحدة من مكتبة Practice الجديدة، من غير ما نملأها بمواقف لمجرد العدد.`,
      anotherWorld: 'جرّب عالم تاني',
      hintTitle: 'الـHints جزء من الـMission نفسها',
      hintBody: 'لما الـmission تبقى live، كل beat هيكون عنده intent واضح، Hint بالعربي، useful words، وfull help عند الحاجة.',
    },
    mission: {
      missingTitle: 'الـMission دي لسه مش جاهزة',
      missingBody: 'ارجع للمكتبة واختار موقف متاح.',
      backPractice: 'الرجوع لـPractice',
      backSituations: 'رجوع للمواقف',
      eyebrow: 'Practice Mission',
      learnerRole: 'أنت',
      ottiRole: 'Otti',
      goal: 'هدفك',
      flowKicker: 'المحادثة مصممة — مش محفوظة',
      flowTitle: 'إيه اللي هتتمرّن عليه؟',
      defaultBeat: 'اتصرف في الموقف بطريقتك',
      firstBeatHelp: 'مش لازم تقول جملة بعينها',
      nextBeatHelp: 'المهم توصل المعنى وتكمل الموقف طبيعي',
      hintTitle: 'الـHint ذكية وبتتعمل وقتها',
      hintBody: 'لو وقفت واضغطت Hint، Otti يبني المساعدة على اللي حصل فعلًا في المحادثة. بنجيب المعنى والكلمات والمثال مرة واحدة، وبعدها أنت تكشف المستوى اللي محتاجه من غير requests زيادة.',
      minutes: (minutes: string) => `حوالي ${minutes} دقائق`,
      liveConversation: 'Live conversation',
      correction: 'التصحيح للغلط الحقيقي فقط',
      start: 'ابدأ الـMission',
    },
    complete: {
      missingTitle: 'Mission completed',
      eyebrow: 'Mission complete',
      title: 'خلصت الموقف',
      body: 'وصلت لنهاية الموقف بنجاح. ده معناه إنك تعاملت مع الـMission دي — مش حكم إن اللغة كلها بقت mastery.',
      arabicHints: 'Hints بالعربي',
      usefulWords: 'Useful words',
      fullHelp: 'Full help',
      usedHelpTitle: 'استخدمت مساعدة؟ ممتاز — ده جزء من التدريب.',
      noHelpTitle: 'المرة دي خلصتها من غير ما تفتح Hint.',
      usedHelpBody: 'لو حابب تقوّي الاستقلال، أعد نفس الموقف وحاول تستخدم مساعدة أقل. مفيش عقوبة على إنك فتحت Hint.',
      noHelpBody: 'ممكن تعيدها تاني وتشوف هل نفس اللغة هتطلع بسهولة، أو ترجع للمكتبة لموقف جديد.',
      retry: 'أعيد الـMission',
      another: 'موقف تاني',
      backPractice: 'الرجوع لـPractice',
    },
  },
} satisfies Record<SupportedLocale, unknown>;

export type PracticeJourneyCopy = typeof practiceJourneyCopy.en;
