import type { PracticeMissionContract } from '../types';

export const A1_ASK_REPEAT_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.everyday.ask-repeat.v1',
  revision: 1,
  slug: 'a1-ask-someone-to-repeat',
  level: 'A1',
  // The app still uses the legacy UI id `everyday`; the authored source world is `everyday-life`.
  worldId: 'everyday',
  titleAr: 'اطلب من الشخص يعيد الكلام',
  titleEn: 'Ask someone to repeat',
  settingAr: 'مدخل نشاط مجتمعي بسيط',
  learnerRoleAr: 'زائر',
  aiRoleAr: 'منظم النشاط',
  goalAr: 'اسمع معلومة قصيرة، اطلب إعادة رقم الأوضة اللي فاتك، اتأكد منه، واقفل الكلام طبيعي.',
  durationMinutes: 3,
  languageGrounding: {
    sourceRepo: 'addvaluewithai-hub/english-course',
    sourceLevel: 'A1',
    inventoryScope: 'cumulative_through_level',
    abilities: [
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p089.a1.asking_for_clarification.001',
        label: 'Can indicate simply that they do not understand.',
        role: 'core clarification/repair grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p089.a1.asking_for_clarification.002',
        label: 'Can express in a simple way that they do not understand.',
        role: 'core clarification/repair grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p074.a1.conversation.001',
        label: 'Can understand concrete everyday expressions when a sympathetic interlocutor speaks clearly, slowly and repeats.',
        role: 'cooperative interlocutor/repetition grounding',
      },
    ],
    grammar: [
      {
        id: 'egp.1741163710391x459074403345042000',
        label: "Use 'can' to make a request.",
        role: 'productive repair opportunity',
      },
    ],
    phrases: [
      { id: 'oxford.phrase.online.0229', label: 'excuse me', role: 'optional polite repair opener' },
      { id: 'oxford.phrase.online.0668', label: 'Thank you', role: 'polite closing' },
    ],
    words: [
      { id: 'oxford.o3000.p01.016', label: 'again', role: 'repair language' },
      { id: 'oxford.o3000.p03.142', label: 'say', role: 'repair language' },
      { id: 'oxford.o3000.p03.132', label: 'room', role: 'scenario language' },
    ],
    runtimeSummaryEn: [
      'Keep the exchange inside short, concrete A1 clarification/repair English.',
      "Natural repair can be very short: 'Sorry?', 'What room?', or 'Again, please.' are valid when the intent is clear.",
      "A fuller model such as 'Can you say the room number again, please?' is useful support, never a required password answer.",
      'The partner is cooperative: repeat clearly and preserve the authored facts instead of manufacturing difficulty.',
      'Grounding controls language quality; it is not a learner checklist.',
    ],
  },
  truthEn: [
    'This is a small community class.',
    'The class starts at six.',
    'The class is in room fifteen.',
    'The learner scenario says the room number was missed and needs to be recovered.',
    'The activity host is cooperative and repeats clearly when asked.',
    'Never change the start time or room number during repetition or confirmation.',
  ],
  canonicalDialogue: [
    { beatId: 'ask_repeat', speaker: 'ai_role', text: 'Hi. The class starts at six in room fifteen.' },
    { beatId: 'ask_repeat', speaker: 'learner', text: 'Sorry. Can you say the room number again, please?' },
    { beatId: 'confirm_detail', speaker: 'ai_role', text: 'Room fifteen.' },
    { beatId: 'confirm_detail', speaker: 'learner', text: 'Room fifteen?' },
    { beatId: 'close', speaker: 'ai_role', text: "Yes, that's right. You're welcome." },
  ],
  surfaceFreedom: 'tight',
  openingMoveEn: [
    'Open on beat ask_repeat.',
    'Silently set the active Practice beat to ask_repeat, then say the authored message once, clearly and naturally: "Hi. The class starts at six in room fifteen."',
    'The learner already knows from the mission setup that the room number was missed. Do not mumble, race, distort pronunciation, or explain the exercise.',
    'After the message, stop and let the learner initiate repair.',
  ].join(' '),
  beats: [
    {
      id: 'ask_repeat',
      type: 'required',
      aiIntentEn: 'Give the short authored message once, then wait for the learner to signal difficulty and request repetition/clarification of the room detail.',
      preferredRealizationsEn: ['Hi. The class starts at six in room fifteen.'],
      learnerIntentEn: 'Signal that the room detail was missed and ask the host to repeat or clarify it.',
      learnerModelsEn: [
        'Sorry. Can you say the room number again, please?',
        'Sorry, what room?',
        'Again, please.',
        'Sorry?',
      ],
      overviewAr: 'اطلب منه يعيد رقم الأوضة',
      correctionFocusEn: [
        'Accept short natural A1 repair language; never force the full canonical request.',
        'If the learner asks to repeat the whole message, that also fulfils the repair intent.',
        'Correct only a genuinely malformed request that makes the repair intent unclear or meaningfully broken.',
      ],
      next: 'confirm_detail',
    },
    {
      id: 'confirm_detail',
      type: 'required',
      aiIntentEn: 'Repeat room fifteen clearly. If the learner requested the whole message, repeat the same short message once. Then let the learner confirm the recovered room detail.',
      preferredRealizationsEn: ['Room fifteen.', "It's room fifteen.", 'The class starts at six in room fifteen.'],
      learnerIntentEn: 'Confirm or clearly demonstrate that the recovered room number is fifteen.',
      learnerModelsEn: ['Room fifteen?', 'Fifteen?', 'Okay, room fifteen.'],
      overviewAr: 'اتأكد إنك سمعت رقم الأوضة صح',
      correctionFocusEn: [
        'If the learner says the wrong room number, repair the factual misunderstanding briefly and keep this beat active; do not label it a grammar error.',
        'Accept a short correct confirmation immediately.',
      ],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Confirm that room fifteen is correct and close briefly and warmly.',
      preferredRealizationsEn: ["Yes, that's right. You're welcome.", "Yes, that's right."],
      learnerIntentEn: 'No further learner move is required after the recovered detail has been confirmed.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 clarification/repair Practice mission. Stay in role as the helpful activity host and never explain the mission engine.',
    'The learner is intentionally told in the setup that the room number was missed. Do not create artificial listening difficulty through mumbling, speed, accent tricks, or changed facts.',
    'The canonical dialogue is the reviewed normal path and language-quality anchor, not a script the learner must reproduce.',
    'Because surface freedom is tight, stay close to the authored message and preferred repair responses on the normal path.',
    'Before each partner turn that creates a learner response opportunity, silently call set_practice_beat with the beat being opened.',
    'Do not advance from ask_repeat until the learner genuinely signals the comprehension problem and requests repetition/clarification.',
    'When that succeeds, advance to confirm_detail and repeat the relevant authored detail clearly. If the learner asked for the whole message, repeat the whole authored message once.',
    'Do not advance from confirm_detail until the learner correctly recovers room fifteen. A wrong number is a factual misunderstanding: repair it briefly, keep the same beat, and let the learner confirm again.',
    'Accept natural A1 alternatives such as Sorry?, What room?, Again, please., Fifteen?, and other clear semantic equivalents.',
    'If there is a genuine English error that blocks the current repair move, give one concise natural correction and let the learner retry before advancing.',
    'Do not correct harmless variation, accent, or every small non-target mistake.',
    'If the learner hesitates, wait. Hints are learner-controlled; never volunteer the repair phrase.',
    'When a UI hint request arrives, generate the whole hint bundle from the conversation as it actually happened and current beat. Do not advance or speak the hint aloud.',
    'Keep spoken turns short, cooperative and concrete.',
  ],
};
