import type { PracticeMissionContract } from '../types';

export const A1_ASK_PLACE_LOCATION_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.travel.ask-place-location.v1',
  revision: 1,
  slug: 'a1-ask-where-a-place-is',
  level: 'A1',
  worldId: 'travel-transport',
  titleAr: 'اسأل مكان فين',
  titleEn: 'Ask where a place is',
  settingAr: 'شارع بسيط في وسط المدينة قريب من كافيه وبنك',
  learnerRoleAr: 'شخص بيدور على البنك',
  aiRoleAr: 'شخص ودود في الشارع',
  goalAr: 'اسأل البنك فين، افهم اتجاه قصير وواضح، اتأكد من التفصيلة الأساسية، واقفل الكلام بأدب.',
  durationMinutes: 4,
  languageGrounding: {
    sourceRepo: 'addvaluewithai-hub/english-course',
    sourceLevel: 'A1',
    inventoryScope: 'cumulative_through_level',
    abilities: [
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p24.005',
        label: 'Can ask for simple directions, referring to a map or plan.',
        role: 'productive direction-request grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p15.004',
        label: 'Can understand simple directions from X to Y on foot or public transport.',
        role: 'receptive direction grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p15.015',
        label: 'Can understand simple directions, if spoken slowly and clearly.',
        role: 'receptive clarity grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p051.a1.understanding_announcements_and_instructions.001',
        label: 'Can understand carefully delivered instructions and short, simple directions.',
        role: 'supportive interlocutor grounding',
      },
    ],
    grammar: [],
    phrases: [
      { id: 'oxford.phrase.online.0229', label: 'excuse me', role: 'polite attention getter' },
      { id: 'oxford.phrase.online.0668', label: 'Thank you', role: 'polite closing' },
    ],
    words: [
      { id: 'oxford.o3000.p01.058', label: 'bank', role: 'destination language' },
      { id: 'oxford.o3000.p02.186', label: 'left', role: 'direction language' },
      { id: 'oxford.o3000.p01.116', label: 'cafe', role: 'landmark language' },
    ],
    runtimeSummaryEn: [
      'Keep the route extremely small and A1-safe: bank, left, next to the cafe.',
      'Speak clearly and naturally; do not add extra landmarks, streets, distances or turns for variety.',
      "A short learner question such as 'The bank, please?' can be valid when the intent is clear in context.",
      'Wrong left/right or landmark recovery is factual repair, not grammar correction.',
      'Grounding controls level and clarity, not exact-answer matching.',
    ],
  },
  truthEn: [
    'The learner is looking for the bank.',
    'The correct direction is left.',
    'The bank is next to the cafe.',
    'The bank is nearby.',
    'Do not add extra streets, turns, distances, transport instructions or conflicting landmarks.',
  ],
  canonicalDialogue: [
    { beatId: 'ask_location', speaker: 'ai_role', text: 'Hello.' },
    { beatId: 'ask_location', speaker: 'learner', text: 'Excuse me. Where is the bank?' },
    { beatId: 'confirm_direction', speaker: 'ai_role', text: 'Go left. The bank is next to the cafe.' },
    { beatId: 'confirm_direction', speaker: 'learner', text: 'Left, next to the cafe?' },
    { beatId: 'close', speaker: 'ai_role', text: "Yes, that's right." },
    { beatId: 'close', speaker: 'learner', text: 'Thank you.' },
    { beatId: 'close', speaker: 'ai_role', text: "You're welcome." },
  ],
  surfaceFreedom: 'tight',
  openingMoveEn: [
    'Open on beat ask_location.',
    'Silently set the active Practice beat to ask_location, then greet the learner very briefly and wait for them to ask for the bank.',
    'Stay close to a simple Hello/Hi. Do not volunteer the route before the learner asks.',
  ].join(' '),
  beats: [
    {
      id: 'ask_location',
      type: 'required',
      aiIntentEn: 'Be available as a friendly passerby and let the learner ask for the nearby bank.',
      preferredRealizationsEn: ['Hello.', 'Hi.'],
      learnerIntentEn: 'Get attention if desired and ask where the bank is.',
      learnerModelsEn: ['Excuse me. Where is the bank?', 'Where is the bank, please?', 'The bank, please?'],
      overviewAr: 'اسأل البنك فين',
      correctionFocusEn: [
        'Accept short natural location requests when the intent is clear.',
        'Do not require Excuse me or one exact where-question form.',
        'Correct only a genuine malformed form that makes the location request clearly broken.',
      ],
      next: 'confirm_direction',
    },
    {
      id: 'confirm_direction',
      type: 'required',
      aiIntentEn: 'Give exactly the short authored route: go left; the bank is next to the cafe.',
      preferredRealizationsEn: ['Go left. The bank is next to the cafe.', "Left. It's next to the cafe."],
      learnerIntentEn: 'Confirm or clearly demonstrate understanding of the left direction and cafe landmark.',
      learnerModelsEn: ['Left, next to the cafe?', 'On the left, next to the cafe?', 'Left?', 'Next to the cafe?'],
      overviewAr: 'اتأكد: شمال وجنب الكافيه',
      correctionFocusEn: [
        'If the learner says right instead of left or changes the landmark, repair the authored fact briefly and keep this beat active.',
        'Treat wrong route information as factual misunderstanding, not grammar error.',
        'Accept short A1 confirmation fragments.',
      ],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Confirm the recovered direction and close politely.',
      preferredRealizationsEn: ["Yes, that's right.", 'Yes. Left, next to the cafe.'],
      learnerIntentEn: 'No further route information is required; an optional thank-you is welcome.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 directions/location Practice mission. Stay in role as a helpful passerby and never explain the mission engine.',
    'Preserve the authored route truth: left, next to the cafe.',
    'Before each partner turn that creates a learner response opportunity, silently call set_practice_beat with the beat being opened.',
    'Do not give the route before the learner has asked where the bank is.',
    'When giving the route, keep it to the authored one-step direction and landmark. Do not invent streets, distances, extra turns, buses, maps or other landmarks.',
    'If the learner says right when the truth is left, repair the factual detail briefly and keep confirm_direction active until the key direction is recovered.',
    'Accept natural short A1 questions and confirmation fragments; canonical wording is not a password.',
    'If a genuine current English error blocks the move, correct briefly and let the learner retry before advancing.',
    'Hints are learner-controlled and contextual to the actual route-recovery moment.',
    'Speak clearly, slowly enough for A1, and keep turns short.',
  ],
};
