import type { PracticeMissionContract } from '../types';

export const A1_MAKE_SIMPLE_PLAN_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.plans.make-simple-plan.v1',
  revision: 1,
  slug: 'a1-make-a-simple-plan',
  level: 'A1',
  worldId: 'plans-leisure',
  titleAr: 'اعمل خطة بسيطة',
  titleEn: 'Make a simple plan',
  settingAr: 'كلام قصير مع صاحبك عن فيلم يوم السبت',
  learnerRoleAr: 'صاحب بيعمل خطة للويك إند',
  aiRoleAr: 'صاحب متعاون',
  goalAr: 'وافق على خروجة بسيطة، اختار الساعة، اتفقوا على مكان المقابلة، واقفلوا والخطة واضحة.',
  durationMinutes: 4,
  languageGrounding: {
    sourceRepo: 'addvaluewithai-hub/english-course',
    sourceLevel: 'A1',
    inventoryScope: 'cumulative_through_level',
    abilities: [
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p15.009',
        label: 'Can understand basic information about free time activities.',
        role: 'leisure activity grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p15.010',
        label: 'Can understand basic questions about free time activities.',
        role: 'simple plan-question grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p111.a1.facilitating_collaborative_interaction_with_peers.001',
        label: "Can invite others' contributions to very simple tasks with short, simple phrases and indicate understanding.",
        role: 'simple collaboration grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p22.003',
        label: 'Can tell the time of day to within five minutes.',
        role: 'time-choice grounding',
      },
    ],
    grammar: [],
    phrases: [],
    words: [
      { id: 'oxford.o3000.p02.041', label: 'film', role: 'activity language' },
      { id: 'oxford.o3000.p03.141', label: 'Saturday', role: 'day language' },
      { id: 'oxford.o3000.p01.143', label: 'cinema', role: 'meeting-place language' },
    ],
    runtimeSummaryEn: [
      'Keep planning cooperative and A1-simple: film on Saturday, choose six or seven, meet at the cinema.',
      'Do not introduce competing schedules, costs, transport, weather, reasons, other people or negotiation.',
      "Short learner choices such as 'Yes', 'Six', 'Seven', or 'At the cinema' are valid in context.",
      'If the learner chooses seven, preserve seven in all later turns and the final recap; never snap back to the canonical six.',
      'Grounding controls interaction and language level, not exact-answer wording.',
    ],
  },
  truthEn: [
    'The activity is seeing a film on Saturday.',
    'The only offered times are six o’clock and seven o’clock.',
    'Either six or seven is valid.',
    'The meeting place is the cinema entrance; equivalent wording such as outside the cinema is acceptable.',
    'The friend is collaborative and has no competing constraints.',
    'Do not add transport, tickets, price, weather, other participants or schedule conflicts.',
  ],
  canonicalDialogue: [
    { beatId: 'agree_activity', speaker: 'ai_role', text: 'Do you want to see a film on Saturday?' },
    { beatId: 'agree_activity', speaker: 'learner', text: 'Yes, that sounds good.' },
    { beatId: 'choose_time', speaker: 'ai_role', text: 'Six or seven?' },
    { beatId: 'choose_time', speaker: 'learner', text: 'Six, please.' },
    { beatId: 'confirm_place', speaker: 'ai_role', text: 'Meet at the cinema?' },
    { beatId: 'confirm_place', speaker: 'learner', text: 'Yes, at the cinema.' },
    { beatId: 'close', speaker: 'ai_role', text: 'Great. Saturday at six, at the cinema.' },
    { beatId: 'close', speaker: 'learner', text: 'Great. See you.' },
  ],
  surfaceFreedom: 'tight',
  openingMoveEn: [
    'Open on beat agree_activity.',
    'Silently set the active Practice beat to agree_activity, then suggest the authored Saturday film plan in one short friendly question.',
    'Stay close to: "Do you want to see a film on Saturday?"',
    'Do not add another activity or constraint on the normal path.',
  ].join(' '),
  beats: [
    {
      id: 'agree_activity',
      type: 'required',
      aiIntentEn: 'Suggest seeing a film on Saturday in one short friendly question.',
      preferredRealizationsEn: ['Do you want to see a film on Saturday?', 'Film on Saturday?'],
      learnerIntentEn: 'Accept the simple Saturday film plan or clearly indicate willingness to go.',
      learnerModelsEn: ['Yes, that sounds good.', 'Yes.', 'Okay, great.', 'A film sounds good.'],
      overviewAr: 'وافق على خروجة الفيلم',
      correctionFocusEn: [
        'A short Yes is fully valid; do not demand a complete sentence.',
        'Do not manufacture conflict or require a reason for accepting.',
        'Correct only a genuine current English error that makes acceptance unclear.',
      ],
      next: 'choose_time',
    },
    {
      id: 'choose_time',
      type: 'required',
      aiIntentEn: 'Offer exactly two times: six or seven.',
      preferredRealizationsEn: ['Six or seven?', "Six o'clock or seven o'clock?"],
      learnerIntentEn: 'Choose either six or seven.',
      learnerModelsEn: ['Six, please.', 'Seven.', "Six o'clock."],
      overviewAr: 'اختار الساعة',
      correctionFocusEn: [
        'Either six or seven is valid and must be remembered for the rest of the mission.',
        'If the learner chooses an unavailable time, restate six or seven and keep this beat active; this is task repair, not grammar correction.',
        'Accept short time-only answers.',
      ],
      next: 'confirm_place',
    },
    {
      id: 'confirm_place',
      type: 'required',
      aiIntentEn: 'Suggest the cinema entrance as the meeting place and ask for confirmation.',
      preferredRealizationsEn: ['Meet at the cinema?', 'At the cinema entrance?'],
      learnerIntentEn: 'Confirm the cinema meeting place or a harmless equivalent such as outside the cinema.',
      learnerModelsEn: ['Yes, at the cinema.', 'At the cinema, yes.', 'Yes.', 'Outside the cinema.'],
      overviewAr: 'أكد مكان المقابلة',
      correctionFocusEn: [
        'Yes alone is valid because the place is explicit in the question.',
        'Accept equivalent public-place wording that preserves the cinema meeting point.',
        'If the learner proposes an unrelated place, clarify the authored cinema meeting place and let them confirm; do not call it a grammar error.',
      ],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Restate the final film/Saturday/selected-time/cinema plan compactly and close warmly.',
      preferredRealizationsEn: ['Great. Saturday at six, at the cinema.', 'Great. Film on Saturday at seven. See you at the cinema.'],
      learnerIntentEn: 'No further planning detail is required; an optional friendly closing is welcome.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 simple-planning Practice mission. Stay in role as a collaborative friend and never explain the mission engine.',
    'Preserve the authored plan: film, Saturday, six or seven, cinema entrance.',
    'Before each AI turn that creates a learner response opportunity, silently call set_practice_beat with the beat being opened.',
    'Do not add competing schedules, transport, ticket price, weather, restaurant plans, other participants, complex preferences or reasons.',
    'Accept either offered time. Once the learner chooses six or seven, preserve that exact choice in all later wording, contextual hints and the final recap.',
    'Accept short natural A1 answers such as Yes, Six, Seven, and At the cinema.',
    'If the learner chooses an unavailable time or unrelated place, handle it as a simple task repair and keep the current beat active rather than calling the English wrong.',
    'If a genuine current English error blocks the move, correct briefly and let the learner retry before advancing.',
    'Hints are learner-controlled and generated from the actual choices already made in the conversation.',
    'Keep turns short and handle one planning decision at a time.',
  ],
};
