import type { PracticeMissionContract } from '../types';

export const A1_MEET_SOMEONE_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.people.meet-someone.v1',
  revision: 1,
  slug: 'a1-meet-someone-new',
  level: 'A1',
  worldId: 'people-social',
  titleAr: 'اتعرف على شخص جديد',
  titleEn: 'Meet someone new',
  settingAr: 'قبل بداية نشاط مجتمعي بسيط',
  learnerRoleAr: 'شخص حاضر النشاط',
  aiRoleAr: 'Maya، مشاركة ودودة في النشاط',
  goalAr: 'سلّم، قول اسم تختاره، رد على سؤال بسيط عن حالك، واسألها هي كمان قبل ما تقفلوا التعارف طبيعي.',
  durationMinutes: 4,
  languageGrounding: {
    sourceRepo: 'addvaluewithai-hub/english-course',
    sourceLevel: 'A1',
    inventoryScope: 'cumulative_through_level',
    abilities: [
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p22.009',
        label: 'Can give key information to introduce themselves, such as their name.',
        role: 'self-introduction grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p22.013',
        label: 'Can greet people, ask how they are and react to news.',
        role: 'greeting and wellbeing grounding',
      },
      {
        id: 'ability.gse_all_objectives.gse.adult.2022.a1.p23.012',
        label: 'Can make an introduction and use basic greeting and leave-taking expressions.',
        role: 'interaction-shape grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p137.a1.sociolinguistic_appropriateness.001',
        label: 'Can establish basic social contact with simple greetings, farewells and introductions.',
        role: 'basic social-contact grounding',
      },
    ],
    grammar: [
      {
        id: 'egp.1741163708329x286701804737242940',
        label: 'Simple affirmative declarative clauses.',
        role: 'basic self-information opportunity',
      },
    ],
    phrases: [
      { id: 'oxford.phrase.online.0346', label: 'How are you?', role: 'wellbeing exchange' },
      { id: 'oxford.phrase.online.0668', label: 'Thank you', role: 'optional polite response' },
    ],
    words: [
      { id: 'oxford.o3000.p02.114', label: 'hello', role: 'greeting language' },
      { id: 'oxford.o3000.p02.262', label: 'name', role: 'introduction language' },
      { id: 'oxford.o3000.p02.086', label: 'good', role: 'wellbeing language' },
      { id: 'oxford.o3000.p02.087', label: 'goodbye', role: 'leave-taking language' },
    ],
    runtimeSummaryEn: [
      'Keep the normal path to a short A1 first-meeting exchange: greeting, names, wellbeing, reciprocal social move, close.',
      "Natural short learner forms such as a bare name, 'Good, thanks', or 'You?' can be valid in context.",
      'The learner may use a real, chosen or fictional name; never require additional personal data.',
      'Do not expand into age, origin, residence, job or contact details; those belong to separate authored missions.',
      'Grounding controls language quality and level, not exact-answer matching.',
    ],
  },
  truthEn: [
    'The AI role is Maya, another friendly attendee at the activity.',
    'Maya is meeting the learner for the first time.',
    'Maya feels good.',
    'The learner may give any plausible chosen or fictional first name.',
    'Use the learner name only if it was clearly understood; otherwise ask one short clarification.',
    'No personal detail beyond a usable chosen name is required.',
  ],
  canonicalDialogue: [
    { beatId: 'exchange_names', speaker: 'ai_role', text: "Hi. I'm Maya. What's your name?" },
    { beatId: 'exchange_names', speaker: 'learner', text: "Hi. I'm Alex." },
    { beatId: 'wellbeing', speaker: 'ai_role', text: 'Nice to meet you, Alex. How are you?' },
    { beatId: 'wellbeing', speaker: 'learner', text: "I'm good, thanks. And you?" },
    { beatId: 'close', speaker: 'ai_role', text: "I'm good, thanks. Nice to meet you." },
    { beatId: 'close', speaker: 'learner', text: 'Nice to meet you too.' },
    { beatId: 'close', speaker: 'ai_role', text: 'See you inside.' },
  ],
  surfaceFreedom: 'tight',
  openingMoveEn: [
    'Open on beat exchange_names.',
    'Silently set the active Practice beat to exchange_names, then greet the learner, introduce yourself as Maya and ask their name in one short turn.',
    'Stay close to: "Hi. I\'m Maya. What\'s your name?"',
    'Do not ask any additional personal question yet.',
  ].join(' '),
  beats: [
    {
      id: 'exchange_names',
      type: 'required',
      aiIntentEn: 'Greet, introduce yourself as Maya, and ask the learner name in one short turn.',
      preferredRealizationsEn: ["Hi. I'm Maya. What's your name?", "Hello. I'm Maya. What's your name?"],
      learnerIntentEn: 'Acknowledge Maya and give a clear chosen or fictional first name.',
      learnerModelsEn: ["Hi. I'm Alex.", 'My name is Alex.', "I'm Alex.", 'Alex.'],
      overviewAr: 'سلّم وقول اسم تختاره',
      correctionFocusEn: [
        'Accept a bare clear name or other short natural A1 form; do not force a full sentence.',
        'If the name itself is unclear, ask once for clarification instead of guessing.',
        'Do not require or probe whether the name is real.',
      ],
      next: 'wellbeing',
    },
    {
      id: 'wellbeing',
      type: 'required',
      aiIntentEn: 'React warmly to the name, say Nice to meet you, then ask one simple wellbeing question.',
      preferredRealizationsEn: ['Nice to meet you. How are you?', 'Nice to meet you, {learner_name}. How are you?'],
      learnerIntentEn: 'Answer the simple wellbeing question and make one reciprocal friendly move back to Maya.',
      learnerModelsEn: ["I'm good, thanks. And you?", 'Good, thanks. How are you?', "I'm fine. And you?", 'Good, thanks. You?'],
      overviewAr: 'رد على السؤال واسألها هي كمان',
      correctionFocusEn: [
        'Accept simple plausible states other than good/fine.',
        'If the learner answers wellbeing but omits the reciprocal move, keep this beat open without calling the answer wrong and create one tiny natural opportunity to return the social attention.',
        'Correct only a genuine current-form error that clearly breaks the social move.',
      ],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Answer the reciprocal wellbeing move briefly and close the first-meeting exchange naturally.',
      preferredRealizationsEn: ["I'm good, thanks. Nice to meet you.", "I'm good, thanks. See you inside."],
      learnerIntentEn: 'No further personal information is required; an optional short friendly closing is welcome.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 first-meeting Practice mission. Stay in role as Maya and never explain the mission engine.',
    'Keep the interaction narrow: greeting, names, wellbeing, reciprocal social contact, close.',
    'Do not turn this into origin, residence, age, job, hobby or contact-detail practice.',
    'The learner may use a real, chosen or fictional name. Never challenge whether it is real.',
    'Use the stated learner name only when clear. If uncertain, ask a short clarification rather than inventing one.',
    'Before each AI turn that opens a learner response opportunity, silently call set_practice_beat with the active beat.',
    'Accept natural A1 alternatives and short forms; the canonical learner lines are examples, not passwords.',
    'If the learner gives a valid wellbeing answer but has not yet made the reciprocal move, remain on wellbeing and leave a minimal natural opening rather than marking the answer wrong.',
    'If a genuine current English error blocks the move, correct briefly and let the learner retry before advancing.',
    'If the learner asks an off-scope personal question, answer very briefly if natural and steer back without opening a new lesson branch.',
    'Hints are learner-controlled and must be contextual to what has actually happened.',
    'Keep turns short, friendly and concrete.',
  ],
};
