import type { PracticeMissionContract } from '../types';

export const A1_ORDER_DRINK_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.food.order-drink.v1',
  revision: 2,
  slug: 'a1-order-a-drink',
  level: 'A1',
  worldId: 'food-shopping',
  titleAr: 'اطلب مشروب',
  titleEn: 'Order a drink',
  settingAr: 'كافيه صغير',
  learnerRoleAr: 'عميل',
  aiRoleAr: 'موظف الكافيه',
  goalAr: 'اطلب مشروب، اختار الحجم، كمّل الدفع، واقفل الطلب بشكل طبيعي.',
  durationMinutes: 4,
  languageGrounding: {
    sourceRepo: 'addvaluewithai-hub/english-course',
    sourceLevel: 'A1',
    inventoryScope: 'cumulative_through_level',
    abilities: [
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p078.a1.obtaining_goods_and_services.001',
        label: 'Can ask people for things and give people things.',
        role: 'supporting transaction grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p078.a1.obtaining_goods_and_services.002',
        label: 'Can ask for food and drink using basic expressions.',
        role: 'core communicative grounding',
      },
      {
        id: 'ability.cefr_all_descriptors.cefr.cv2020.p078.a1.obtaining_goods_and_services.003',
        label: 'Can handle numbers, quantities, cost and time.',
        role: 'price and size grounding',
      },
    ],
    grammar: [
      {
        id: 'egp.1741163710391x459074403345042000',
        label: "Use 'can' to make a request.",
        role: 'productive opportunity',
      },
      {
        id: 'egp.1741163711300x569087712695511000',
        label: "Use 'would like' for wishes and preferences.",
        role: 'productive or receptive alternative',
      },
    ],
    phrases: [
      { id: 'oxford.phrase.online.0076', label: 'ask for sth', role: 'functional grounding' },
      { id: 'oxford.phrase.online.0668', label: 'Thank you', role: 'closing and politeness' },
    ],
    words: [
      { id: 'oxford.o3000.p01.154', label: 'coffee' },
      { id: 'oxford.o3000.p03.237', label: 'tea' },
      { id: 'oxford.o3000.p04.054', label: 'water' },
      { id: 'oxford.o3000.p03.183', label: 'small' },
      { id: 'oxford.o3000.p02.179', label: 'large' },
      { id: 'oxford.o3000.p01.214', label: 'dollar' },
      { id: 'oxford.o3000.p03.077', label: 'please' },
    ],
    runtimeSummaryEn: [
      'Keep normal-path language inside simple A1 service English.',
      "Useful request anchors include 'Can I have ...?' and 'I'd like ...', but short natural requests such as 'Coffee, please' are also valid.",
      "Use the reviewed item words coffee, tea, water, small, large, dollar and please where they naturally fit.",
      'Price language should remain short, concrete and easy to hear.',
      'Grounding controls language quality; it is not a checklist the learner must reproduce.',
    ],
  },
  truthEn: [
    'The cafe has coffee, tea and water only.',
    'Coffee: small $3, large $4.',
    'Tea: small $2, large $3.',
    'Water: small $1, large $2.',
    'Available sizes are small and large only.',
  ],
  canonicalDialogue: [
    { beatId: 'greet_order', speaker: 'ai_role', text: 'Hello. What would you like?' },
    { beatId: 'greet_order', speaker: 'learner', text: 'Can I have a coffee, please?' },
    { beatId: 'choose_size', speaker: 'ai_role', text: 'Small or large?' },
    { beatId: 'choose_size', speaker: 'learner', text: 'Small, please.' },
    { beatId: 'price', speaker: 'ai_role', text: 'Three dollars, please.' },
    { beatId: 'price', speaker: 'learner', text: 'Okay. Thank you.' },
    { beatId: 'close', speaker: 'ai_role', text: 'Thank you.' },
  ],
  surfaceFreedom: 'tight',
  openingMoveEn: [
    'Open on beat greet_order.',
    "On the normal path, prefer the authored opening 'Hello. What would you like?' or the reviewed alternative 'Hi. What can I get for you?'.",
    'Before speaking, silently set the active practice beat to greet_order.',
  ].join(' '),
  beats: [
    {
      id: 'greet_order',
      type: 'required',
      aiIntentEn: 'Greet the customer naturally and ask what they would like to order.',
      preferredRealizationsEn: ['Hello. What would you like?', 'Hi. What can I get for you?'],
      learnerIntentEn: 'Request one available drink politely.',
      learnerModelsEn: ['Can I have a coffee, please?', "I'd like a tea, please.", 'Water, please.'],
      overviewAr: 'اطلب المشروب اللي عايزه',
      correctionFocusEn: [
        'Correct only a genuine request-form error or wording that is unclear enough to block the order.',
        'Do not correct a valid alternative just because it differs from the canonical dialogue or learner models.',
        'Short natural A1 requests are valid when they complete the transaction.',
      ],
      next: 'choose_size',
    },
    {
      id: 'choose_size',
      type: 'required',
      aiIntentEn: 'Ask whether the learner wants a small or large size.',
      preferredRealizationsEn: ['Small or large?'],
      learnerIntentEn: 'Choose one offered size.',
      learnerModelsEn: ['Small, please.', 'Large, please.'],
      overviewAr: 'اختار الحجم',
      correctionFocusEn: [
        'Correct only if the learner answer is genuinely malformed or unclear.',
        'Short natural A1 answers are fully valid.',
      ],
      next: 'price',
    },
    {
      id: 'price',
      type: 'required',
      aiIntentEn: 'State the correct price for the chosen drink and size in one short sentence, then allow the learner to complete the exchange.',
      preferredRealizationsEn: ['<correct number> dollars, please.'],
      learnerIntentEn: 'Acknowledge the price and complete the payment exchange politely.',
      learnerModelsEn: ['Okay. Thank you.', 'Thank you.'],
      overviewAr: 'كمّل الدفع واقفل الطلب',
      correctionFocusEn: ['Do not demand a long sentence when a short natural response completes the transaction.'],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Give one short natural closing line confirming/closing the transaction.',
      preferredRealizationsEn: ['Thank you.'],
      learnerIntentEn: 'Optional polite closing.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 Practice mission. Stay in role as the cafe cashier; do not explain the exercise.',
    'The canonical dialogue is the reviewed normal path and language-quality anchor. It is not a script the learner must reproduce.',
    'Because surface freedom is tight, stay close to canonical/preferred AI wording on the normal path instead of inventing stylistic alternatives merely for variety.',
    'Adapt wording when the learner makes a valid alternative move, asks a reasonable question, needs clarification/correction, or selects an unavailable item.',
    'Follow the authored beat order and semantic intents. Never require exact canonical learner wording.',
    'Before each partner turn that creates a learner response opportunity, silently call set_practice_beat with the beat you are opening.',
    'Do not advance to the next beat until the learner has genuinely completed the current communicative intent.',
    'If clarification or a retry is needed, keep the same beat active.',
    'If the learner says something different but correct and natural, accept it.',
    'If there is a genuine current-beat English error, give one concise correction with a natural A1 form and let the learner retry before advancing.',
    'Do not correct harmless variation, accent, or every small non-target mistake.',
    'If the learner hesitates, wait. Hints are generated only when the learner taps Hint; never volunteer a target sentence.',
    'When a UI hint request arrives, generate the whole hint bundle from the conversation as it actually happened. Prefer the mission language grounding and learner models when they fit the current context, but never treat them as password answers.',
    'Keep every spoken turn short and ask one thing at a time.',
    'Never invent menu items, sizes or prices outside scenario truth.',
    'When the learner completes the price/payment beat, set the beat to close and give one brief natural closing line. Ask no new question after that.',
  ],
};
