import type { PracticeMissionContract } from '../types';

export const A1_ORDER_DRINK_MISSION: PracticeMissionContract = {
  sourceId: 'practice.a1.food.order-drink.v1',
  revision: 1,
  slug: 'a1-order-a-drink',
  level: 'A1',
  worldId: 'food-shopping',
  titleAr: 'اطلب مشروب',
  titleEn: 'Order a drink',
  settingAr: 'كافيه صغير',
  learnerRoleAr: 'عميل',
  aiRoleAr: 'موظف الكافيه',
  goalAr: 'اطلب مشروب، اختار الحجم، كمّل الدفع، واقفل الطلب بشكل طبيعي.',
  durationMinutes: 4,
  truthEn: [
    'The cafe has coffee, tea and water only.',
    'Coffee: small $3, large $4.',
    'Tea: small $2, large $3.',
    'Water: small $1, large $2.',
    'Available sizes are small and large only.',
  ],
  openingMoveEn: 'Open naturally as the cafe cashier with one short greeting and ask what the customer would like. Before speaking, silently set the active practice beat to greet_order.',
  beats: [
    {
      id: 'greet_order',
      type: 'required',
      aiIntentEn: 'Greet the customer naturally and ask what they would like to order.',
      learnerIntentEn: 'Request one available drink politely.',
      intentHintAr: 'اطلب مشروب',
      usefulLanguageEn: ["I'd like ...", 'Can I have ...?', 'please'],
      fullHelpExamplesEn: ["I'd like a coffee, please.", 'Can I have a tea, please?'],
      correctionFocusEn: [
        'Correct only a genuine request-form error or wording that is unclear enough to block the order.',
        'Do not correct a valid alternative just because it differs from the examples.',
      ],
      next: 'choose_size',
    },
    {
      id: 'choose_size',
      type: 'required',
      aiIntentEn: 'Ask whether the learner wants a small or large size.',
      learnerIntentEn: 'Choose one offered size.',
      intentHintAr: 'اختار الحجم',
      usefulLanguageEn: ['small', 'large', 'please'],
      fullHelpExamplesEn: ['Small, please.', 'A large one, please.'],
      correctionFocusEn: [
        'Correct only if the learner answer is genuinely malformed or unclear.',
        'Short natural A1 answers are fully valid.',
      ],
      next: 'price',
    },
    {
      id: 'price',
      type: 'required',
      aiIntentEn: 'State the correct price for the chosen drink and size, then allow the learner to complete the exchange.',
      learnerIntentEn: 'Acknowledge the price and complete the payment exchange politely.',
      intentHintAr: 'وافق وكمل الطلب',
      usefulLanguageEn: ['okay', 'thanks', 'here you are'],
      fullHelpExamplesEn: ['Okay, thanks.', 'Here you are. Thanks.'],
      correctionFocusEn: ['Do not demand a long sentence when a short natural response completes the transaction.'],
      next: 'close',
    },
    {
      id: 'close',
      type: 'ending',
      aiIntentEn: 'Give one short natural closing line, such as confirming the order or thanking the customer.',
      learnerIntentEn: 'Optional polite closing.',
    },
  ],
  promptPolicyEn: [
    'This is an authored A1 Practice mission. Stay in role as the cafe cashier; do not explain the exercise.',
    'Follow the authored beat order, but phrase each turn naturally instead of reading a fixed dialogue.',
    'Before each partner turn that creates a learner response opportunity, silently call set_practice_beat with the beat you are opening.',
    'Do not advance to the next beat until the learner has genuinely completed the current communicative intent.',
    'If clarification or a retry is needed, keep the same beat active.',
    'If the learner says something different but correct and natural, accept it. Never require exact wording from the full-help examples.',
    'If there is a genuine current-beat English error, give one concise correction with a natural correct form and let the learner retry before advancing.',
    'Do not correct harmless variation, accent, or every small non-target mistake.',
    'If the learner hesitates, wait. The learner controls the UI hint ladder; do not reveal the target answer unless they ask you directly for help.',
    'Keep every spoken turn short and ask one thing at a time.',
    'Never invent menu items, sizes or prices outside scenario truth.',
    'When the learner completes the price/payment beat, set the beat to close and give one brief natural closing line. Ask no new question after that.',
  ],
};
