import type { LearnV2Lesson } from './catalog';

export const A1_LEARN_V2_LESSONS: LearnV2Lesson[] = [
  {
    id: 'a1-u1-l01',
    level: 'A1',
    unit: 1,
    lesson: 1,
    code: 'A1 • U1-L01',
    titleEn: "Hello. I'm …",
    titleAr: 'أول تعارف بسيط',
    estimatedMinutes: 9,
    goalAr: 'بعد الدرس ده هتقدر تسلّم على شخص، تقول اسمك، تسأل عن اسمه، وتتعامل مع How are you? بشكل طبيعي.',
    goalExample: ['Hi! I’m Maya.', 'Hello! I’m Adam.'],
    prepIntroAr: 'مش محتاج تحفظ حوار كامل. جهّز القطع الصغيرة دي الأول، وبعدها هتسمعها وتستخدمها بنفسك.',
    prepItems: [
      { id: 'hi', english: 'Hi / Hello', meaningAr: 'أهلاً / مرحبًا', exampleEn: 'Hi! I’m Adam.', role: 'use' },
      { id: 'good-morning', english: 'Good morning', meaningAr: 'صباح الخير', exampleEn: 'Good morning!', role: 'use' },
      { id: 'im', english: 'I’m …', meaningAr: 'أنا …', exampleEn: 'I’m Salma.', noteAr: 'I’m هي الشكل الطبيعي المختصر لـ I am في الكلام.', role: 'use' },
      { id: 'my-name', english: 'My name is …', meaningAr: 'اسمي …', exampleEn: 'My name is Omar.', role: 'use' },
      { id: 'whats-your-name', english: 'What’s your name?', meaningAr: 'اسمك إيه؟', exampleEn: 'Hi. What’s your name?', role: 'use' },
      { id: 'how-are-you', english: 'How are you?', meaningAr: 'عامل إيه؟ / أخبارك إيه؟', exampleEn: 'Hi, Sara. How are you?', role: 'use' },
      { id: 'wellbeing', english: 'I’m good / fine / okay, thanks.', meaningAr: 'أنا كويس، شكرًا.', exampleEn: 'I’m good, thanks.', role: 'use' },
      { id: 'thanks', english: 'Thank you / Thanks', meaningAr: 'شكرًا', exampleEn: 'Fine, thanks.', role: 'use' },
    ],
    move: {
      eyebrowAr: 'الفكرة الصغيرة',
      titleAr: 'التعارف مش محتاج سكريبت طويل',
      introAr: 'أربع حركات بسيطة كفاية عشان تبدأ. الترتيب مش قانون؛ هو بس خريطة تساعدك في أول مرة.',
      steps: [
        { labelEn: 'Greet', explanationAr: 'ابدأ بتحية قصيرة.' },
        { labelEn: 'Say your name', explanationAr: 'قول اسمك بجملة بسيطة.' },
        { labelEn: 'Ask', explanationAr: 'اسأل الطرف التاني عن اسمه.' },
        { labelEn: 'Respond', explanationAr: 'اتعامل مع How are you? برد قصير طبيعي.' },
      ],
      example: [
        { speaker: 'A', text: 'Hi! I’m Yasser.' },
        { speaker: 'B', text: 'Hello! I’m Maya.' },
        { speaker: 'A', text: 'How are you?' },
        { speaker: 'B', text: 'I’m good, thanks.' },
      ],
      noteAr: 'ده مثال، مش script مطلوب تحفظه. في المحادثة الحقيقية ممكن الترتيب يتغير.',
      languageNote: [
        { form: 'I’m = I am', explanationAr: 'في الكلام الطبيعي الاختصار شائع جدًا.' },
        { form: 'What’s = What is', explanationAr: 'هتسمع الشكل المختصر أكتر في المحادثة.' },
      ],
    },
    listeningIntroAr: 'اسمع تعارف قصير بين شخصين. أول مرة اسمع للمعنى فقط؛ وبعدها جاوب سؤالين بسيطين.',
    listeningClips: [
      {
        id: 'a1-u1-l01-first-meeting',
        titleAr: 'أول يوم في مكان جديد',
        subtitleAr: 'Maya و Adam بيتقابلوا لأول مرة.',
        speakers: [{ speaker: 'Maya', voice: 'Kore' }, { speaker: 'Adam', voice: 'Puck' }],
        turns: [
          { speaker: 'Maya', text: 'Hi! Good morning.', style: 'friendly, slightly nervous, clear and unhurried' },
          { speaker: 'Adam', text: 'Morning! I’m Adam. What’s your name?', style: 'warm, relaxed and friendly' },
          { speaker: 'Maya', text: 'I’m Maya.', style: 'friendly, slightly nervous' },
          { speaker: 'Adam', text: 'Hi, Maya. How are you?', style: 'warm and interested' },
          { speaker: 'Maya', text: 'I’m good, thanks. A little nervous, actually.', style: 'honest, slightly nervous' },
          { speaker: 'Adam', text: 'Me too. First day!', style: 'light, reassuring and friendly' },
        ],
        questions: [
          { id: 'adam-name', promptAr: 'اسم الشخص التاني إيه؟', options: ['Adam', 'Maya', 'Omar'], answerIndex: 0, feedbackAr: 'صح — هو قال: “I’m Adam.”' },
          { id: 'maya-feeling', promptAr: 'Maya حاسة بإيه؟', options: ['Angry', 'A little nervous', 'Very tired'], answerIndex: 1, feedbackAr: 'صح — قالت إنها كويسة، بس nervous شوية.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l01',
    missionTitleAr: 'قابل شخص لأول مرة',
    missionSetupAr: 'إنت في English meetup صغير. Otti شخص أول مرة تقابله. مفيش إجابة نموذجية قدامك — خليك بسيط واستخدم اللي يناسبك.',
    missionUsefulLanguage: ['Hi / Hello', 'I’m …', 'What’s your name?', 'How are you?', 'I’m good, thanks.'],
    sourceNoteAr: 'A1 U1-L01: greet, exchange names, basic wellbeing and politeness. باقي الـsource records دعم للمهمة، مش mini-lessons منفصلة.',
  },
  {
    id: 'a1-u1-l02',
    level: 'A1',
    unit: 1,
    lesson: 2,
    code: 'A1 • U1-L02',
    titleEn: 'How old are you?',
    titleAr: 'العمر والأرقام اللي تحتاجها',
    estimatedMinutes: 8,
    goalAr: 'بعد الدرس ده هتقدر تسأل عن العمر، تقول عمرك، وتفهم أرقام بسيطة في نفس السياق من غير ما نحول الدرس لفصل أرقام كامل.',
    goalExample: ['How old are you?', 'I’m twenty-two.'],
    prepIntroAr: 'المنهج فيه عدد كبير من number records هنا، لكن الأداء المطلوب بسيط: سؤال العمر + رقم مفهوم. هنركّز على الـpattern ونسمع كام contrast مهم.',
    prepItems: [
      { id: 'age-question', english: 'How old are you?', meaningAr: 'عندك كام سنة؟', exampleEn: 'How old are you?', role: 'use' },
      { id: 'age-short', english: 'I’m twenty-two.', meaningAr: 'عندي 22 سنة.', exampleEn: 'I’m twenty-two.', role: 'use' },
      { id: 'years-old', english: '… years old', meaningAr: '… سنة من العمر', exampleEn: 'I’m twenty-two years old.', noteAr: 'ينفع تقول الرقم بس بعد I’m، أو تضيف years old.', role: 'use' },
      { id: 'teen-ty', english: 'thirteen / thirty', meaningAr: '13 / 30', exampleEn: 'She’s thirteen. He’s thirty.', noteAr: 'اسمع مكان الـstress؛ الفرق مهم في الأرقام اللي شبه بعض.', role: 'hear' },
      { id: 'fourteen-forty', english: 'fourteen / forty', meaningAr: '14 / 40', exampleEn: 'Fourteen, not forty.', role: 'hear' },
    ],
    move: {
      eyebrowAr: 'Pattern',
      titleAr: 'العمر مع be، مش have',
      introAr: 'في الإنجليزية بنقول I’m + age. مش بنترجم العربي حرفيًا.',
      steps: [
        { labelEn: 'Ask', explanationAr: 'How old are you?' },
        { labelEn: 'Answer', explanationAr: 'I’m + number.' },
        { labelEn: 'Optional', explanationAr: 'ممكن تضيف years old لو حبيت.' },
      ],
      example: [
        { speaker: 'A', text: 'How old are you?' },
        { speaker: 'B', text: 'I’m nineteen.' },
      ],
      noteAr: 'المهم إن الرقم يبقى واضح ومفهوم. مش محتاج تحفظ قائمة أرقام منفصلة قبل ما تتكلم.',
      languageNote: [
        { form: 'I’m 19.', explanationAr: 'طبيعي وكامل في الكلام.' },
        { form: 'I have 19 years. ✕', explanationAr: 'ما ننقلش تركيب العربي/لغات تانية حرفيًا.' },
      ],
    },
    listeningIntroAr: 'اسمع شخصين بيتعارفوا وركّز على الأرقام، خصوصًا إن بعض الأرقام صوتها قريب.',
    listeningClips: [
      {
        id: 'a1-u1-l02-age-chat',
        titleAr: 'زمايل جدد',
        subtitleAr: 'Lina و Sam بيتكلموا عن العمر.',
        speakers: [{ speaker: 'Lina', voice: 'Kore' }, { speaker: 'Sam', voice: 'Puck' }],
        turns: [
          { speaker: 'Lina', text: 'Hi, I’m Lina. How old are you?', style: 'friendly, clear and unhurried' },
          { speaker: 'Sam', text: 'I’m nineteen. What about you?', style: 'relaxed and clear' },
          { speaker: 'Lina', text: 'I’m twenty-two.', style: 'friendly' },
          { speaker: 'Sam', text: 'Oh, my brother is twenty-two too.', style: 'light and conversational' },
        ],
        questions: [
          { id: 'sam-age', promptAr: 'Sam عنده كام سنة؟', options: ['19', '29', '30'], answerIndex: 0, feedbackAr: 'صح — قال: “I’m nineteen.”' },
          { id: 'lina-age', promptAr: 'Lina عندها كام سنة؟', options: ['20', '22', '32'], answerIndex: 1, feedbackAr: 'صح — قالت: “I’m twenty-two.”' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l02',
    missionTitleAr: 'اسأل وقول العمر',
    missionSetupAr: 'إنت بتتعرف على زميل جديد. استخدم عمر حقيقي أو خيالي براحتك؛ المهم تسأل وتجاوب وتتعامل مع رقم مسموع.',
    missionUsefulLanguage: ['How old are you?', 'I’m …', '… years old', 'Sorry, thirteen or thirty?'],
    sourceNoteAr: 'A1 U1-L02: give/understand age and basic functional numbers. الأرقام الواسعة support للسياق، مش vocabulary dump.',
  },
  {
    id: 'a1-u1-l03',
    level: 'A1',
    unit: 1,
    lesson: 3,
    code: 'A1 • U1-L03',
    titleEn: 'Where are you from?',
    titleAr: 'منين وعايش فين',
    estimatedMinutes: 9,
    goalAr: 'بعد الدرس ده هتقدر تسأل وتقول بلد الأصل ومكان السكن، وتفهم الفرق بين where you are from وwhere you live.',
    goalExample: ['I’m from Egypt.', 'I live in Dubai.'],
    prepIntroAr: 'هنا فيه فرق صغير لكنه مهم: مكان الأصل ومكان السكن ممكن يكونوا نفس المكان أو مكانين مختلفين.',
    prepItems: [
      { id: 'where-from', english: 'Where are you from?', meaningAr: 'إنت منين؟', exampleEn: 'Where are you from?', role: 'use' },
      { id: 'im-from', english: 'I’m from …', meaningAr: 'أنا من …', exampleEn: 'I’m from Egypt.', role: 'use' },
      { id: 'come-from', english: 'come from …', meaningAr: 'أكون أصلي من …', exampleEn: 'I come from Jordan.', role: 'use' },
      { id: 'where-live', english: 'Where do you live?', meaningAr: 'ساكن فين؟', exampleEn: 'Where do you live?', role: 'use' },
      { id: 'live-in', english: 'I live in …', meaningAr: 'أنا ساكن في …', exampleEn: 'I live in Cairo.', role: 'use' },
      { id: 'country', english: 'country', meaningAr: 'بلد / دولة', exampleEn: 'Egypt is a country.', role: 'hear' },
      { id: 'city', english: 'city', meaningAr: 'مدينة', exampleEn: 'Cairo is a city.', role: 'hear' },
    ],
    move: {
      eyebrowAr: 'Meaning',
      titleAr: 'from مش هي live',
      introAr: 'سؤالين شبه بعض لكن كل واحد بيسأل عن معلومة مختلفة.',
      steps: [
        { labelEn: 'from', explanationAr: 'الأصل أو البلد اللي جاي منها.' },
        { labelEn: 'live', explanationAr: 'المكان اللي ساكن فيه دلوقتي.' },
        { labelEn: 'Both can differ', explanationAr: 'ممكن تكون from Alexandria وتعيش in Cairo مثلًا.' },
      ],
      example: [
        { speaker: 'A', text: 'Where are you from?' },
        { speaker: 'B', text: 'I’m from Jordan, but I live in Dubai.' },
      ],
      noteAr: 'مش محتاج تحفظ أسماء بلاد كتير. استخدم الأماكن اللي تهمك، والباقي هتقابله مع الوقت.',
      languageNote: [
        { form: 'I’m from Egypt.', explanationAr: 'الأصل.' },
        { form: 'I live in Cairo.', explanationAr: 'السكن الحالي.' },
      ],
    },
    listeningIntroAr: 'اسمع شخصين عندهم origin وresidence مختلفين، وميّز كل معلومة لوحدها.',
    listeningClips: [
      {
        id: 'a1-u1-l03-origin-home',
        titleAr: 'من بلد وعايش في بلد تانية',
        subtitleAr: 'Mariam و Alex بيتبادلوا معلومات بسيطة.',
        speakers: [{ speaker: 'Mariam', voice: 'Aoede' }, { speaker: 'Alex', voice: 'Charon' }],
        turns: [
          { speaker: 'Mariam', text: 'Where are you from, Alex?', style: 'friendly and clear' },
          { speaker: 'Alex', text: 'I’m from Spain, but I live in London now. What about you?', style: 'relaxed and clear' },
          { speaker: 'Mariam', text: 'I’m from Egypt. I live in Dubai.', style: 'warm and unhurried' },
          { speaker: 'Alex', text: 'Oh, nice.', style: 'friendly and light' },
        ],
        questions: [
          { id: 'alex-origin', promptAr: 'Alex أصله منين؟', options: ['Spain', 'London', 'Dubai'], answerIndex: 0, feedbackAr: 'صح — هو from Spain.' },
          { id: 'mariam-live', promptAr: 'Mariam عايشة فين دلوقتي؟', options: ['Egypt', 'Spain', 'Dubai'], answerIndex: 2, feedbackAr: 'صح — قالت: “I live in Dubai.”' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l03',
    missionTitleAr: 'تعارف دولي بسيط',
    missionSetupAr: 'قابل شخص في meetup دولي. استخدم معلوماتك الحقيقية أو اختر بلد ومدينة خياليين. المطلوب تفرق بين الأصل والسكن وتسأل الطرف التاني كمان.',
    missionUsefulLanguage: ['Where are you from?', 'I’m from …', 'Where do you live?', 'I live in …'],
    sourceNoteAr: 'A1 U1-L03: ask/say/understand origin and residence. الهدف exchange مفهوم، مش حفظ قائمة دول ومدن.',
  },
  {
    id: 'a1-u1-l04',
    level: 'A1',
    unit: 1,
    lesson: 4,
    code: 'A1 • U1-L04',
    titleEn: 'What do you do?',
    titleAr: 'شغل ولا دراسة؟',
    estimatedMinutes: 9,
    goalAr: 'بعد الدرس ده هتقدر تقول وتفهم معلومة بسيطة عن الشغل أو الدراسة من غير ما تحفظ 23 وظيفة كأنهم قائمة امتحان.',
    goalExample: ['I’m a student.', 'I work as a designer.'],
    prepIntroAr: 'هنختار active core صغير للقول، وباقي أسماء الوظائف يكفي تتعرف عليها لما تسمعها في الأول.',
    prepItems: [
      { id: 'what-do-you-do', english: 'What do you do?', meaningAr: 'بتشتغل إيه؟ / بتعمل إيه في حياتك؟', exampleEn: 'What do you do?', role: 'use' },
      { id: 'student', english: 'I’m a student.', meaningAr: 'أنا طالب.', exampleEn: 'I’m a student.', role: 'use' },
      { id: 'teacher', english: 'I’m a teacher.', meaningAr: 'أنا مدرس.', exampleEn: 'I’m a teacher.', role: 'use' },
      { id: 'work-as', english: 'I work as …', meaningAr: 'أنا بشتغل كـ …', exampleEn: 'I work as a designer.', role: 'use' },
      { id: 'work-for', english: 'I work for …', meaningAr: 'أنا بشتغل لدى / في شركة …', exampleEn: 'I work for a small company.', role: 'use' },
      { id: 'study', english: 'I study …', meaningAr: 'أنا بدرس …', exampleEn: 'I study engineering.', role: 'use' },
      { id: 'doctor', english: 'doctor', meaningAr: 'طبيب', exampleEn: 'She’s a doctor.', role: 'hear' },
      { id: 'engineer', english: 'engineer', meaningAr: 'مهندس', exampleEn: 'He’s an engineer.', role: 'hear' },
      { id: 'nurse', english: 'nurse', meaningAr: 'ممرض / ممرضة', exampleEn: 'She works as a nurse.', role: 'hear' },
      { id: 'driver', english: 'driver', meaningAr: 'سائق', exampleEn: 'He’s a driver.', role: 'hear' },
      { id: 'designer', english: 'designer', meaningAr: 'مصمم', exampleEn: 'I work as a designer.', role: 'hear' },
    ],
    move: {
      eyebrowAr: 'Choose a frame',
      titleAr: 'قول الحقيقة بأقصر frame مناسب',
      introAr: 'مش كل شخص محتاج نفس الجملة؛ طالب غير موظف غير شخص عايز يذكر الشركة.',
      steps: [
        { labelEn: 'I’m a …', explanationAr: 'لما اسم الوظيفة هو أهم معلومة.' },
        { labelEn: 'I work as …', explanationAr: 'لما بتتكلم عن دورك أو مهنتك.' },
        { labelEn: 'I work for …', explanationAr: 'لما المكان أو الشركة مهمين.' },
        { labelEn: 'I study …', explanationAr: 'لو أنت طالب وعايز تقول مجال الدراسة.' },
      ],
      example: [
        { speaker: 'A', text: 'What do you do?' },
        { speaker: 'B', text: 'I’m a student. I study engineering.' },
      ],
      noteAr: 'الهدف إنك توصل معلومة واحدة واضحة. مش مطلوب تستخدم كل frames في نفس الإجابة.',
    },
    listeningIntroAr: 'اسمع شخصين في event بسيط وحدد كل واحد بيشتغل أو بيدرس إيه.',
    listeningClips: [
      {
        id: 'a1-u1-l04-work-study',
        titleAr: 'في event صغير',
        subtitleAr: 'Nora و Karim بيتعرفوا على شغل ودراسة بعض.',
        speakers: [{ speaker: 'Nora', voice: 'Kore' }, { speaker: 'Karim', voice: 'Puck' }],
        turns: [
          { speaker: 'Nora', text: 'What do you do, Karim?', style: 'friendly and clear' },
          { speaker: 'Karim', text: 'I’m a student. I study engineering. What about you?', style: 'relaxed and clear' },
          { speaker: 'Nora', text: 'I work as a nurse at a small hospital.', style: 'warm and unhurried' },
          { speaker: 'Karim', text: 'Oh, nice.', style: 'friendly' },
        ],
        questions: [
          { id: 'karim-role', promptAr: 'Karim بيعمل إيه؟', options: ['طالب هندسة', 'طبيب', 'سائق'], answerIndex: 0, feedbackAr: 'صح — هو student وبيدرس engineering.' },
          { id: 'nora-role', promptAr: 'Nora بتشتغل إيه؟', options: ['teacher', 'nurse', 'designer'], answerIndex: 1, feedbackAr: 'صح — قالت: “I work as a nurse.”' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l04',
    missionTitleAr: 'اتكلم عن شغلك أو دراستك',
    missionSetupAr: 'إنت في networking event بسيط. قول معلومة واحدة أو اتنين عن شغلك/دراستك، واسأل الطرف التاني. ينفع تستخدم شخصية خيالية لو مش عايز معلومات شخصية.',
    missionUsefulLanguage: ['What do you do?', 'I’m a …', 'I work as …', 'I work for …', 'I study …'],
    sourceNoteAr: 'A1 U1-L04: give/understand a job or study fact. الـ23 words جوه profiles ومواقف، مش recall list.',
  },
  {
    id: 'a1-u1-l05',
    level: 'A1',
    unit: 1,
    lesson: 5,
    code: 'A1 • U1-L05',
    titleEn: 'Can you spell that?',
    titleAr: 'بيانات التواصل وإصلاح سوء الفهم',
    estimatedMinutes: 10,
    goalAr: 'بعد الدرس ده هتقدر تتبادل phone/email/address بسيط، والأهم تعرف تصلّح الموقف لو اسم أو رقم مش واضح بدل ما تخمّن.',
    goalExample: ['How do you spell that?', 'Can you say that again?'],
    prepIntroAr: 'الدرس مش عن حفظ كلمات contact بس؛ المهارة الحقيقية إنك توقف وتطلب clarification لما معلومة مهمة ماوصلتش.',
    prepItems: [
      { id: 'phone-number', english: 'phone number', meaningAr: 'رقم التليفون', exampleEn: 'What’s your phone number?', role: 'use' },
      { id: 'email-address', english: 'email address', meaningAr: 'البريد الإلكتروني', exampleEn: 'What’s your email address?', role: 'use' },
      { id: 'address', english: 'address', meaningAr: 'العنوان', exampleEn: 'What’s your address?', role: 'hear' },
      { id: 'spell', english: 'How do you spell that?', meaningAr: 'بتهجّي ده إزاي؟', exampleEn: 'Sorry, how do you spell Hassan?', role: 'use' },
      { id: 'say-again', english: 'Can you say that again?', meaningAr: 'ممكن تقولها تاني؟', exampleEn: 'Sorry, can you say that again?', role: 'use' },
      { id: 'write-down', english: 'Can you write it down?', meaningAr: 'ممكن تكتبه؟', exampleEn: 'Can you write it down, please?', role: 'use' },
      { id: 'at', english: 'at', meaningAr: '@ في الإيميل', exampleEn: 'maya at example dot com', role: 'hear' },
      { id: 'dot', english: 'dot', meaningAr: 'نقطة في الإيميل', exampleEn: 'example dot com', role: 'hear' },
    ],
    move: {
      eyebrowAr: 'Repair move',
      titleAr: 'لو المعلومة مهمة: ما تخمّنش',
      introAr: 'رقم أو اسم غلط ممكن يبوّظ المهمة كلها. الإصلاح البسيط جزء من التواصل الطبيعي.',
      steps: [
        { labelEn: 'Stop', explanationAr: 'لو مش متأكد، متكملش كأنك فهمت.' },
        { labelEn: 'Repair', explanationAr: 'اطلب repeat أو spelling أو كتابة.' },
        { labelEn: 'Confirm', explanationAr: 'كرر الجزء المهم لو محتاج تتأكد.' },
      ],
      example: [
        { speaker: 'A', text: 'My email is samir.hassan@example.com.' },
        { speaker: 'B', text: 'Sorry, how do you spell Hassan?' },
        { speaker: 'A', text: 'H-A-S-S-A-N.' },
      ],
      noteAr: 'طلب التوضيح مش علامة إن إنجليزيتك ضعيفة؛ ده skill مطلوب في المنهج نفسه.',
    },
    listeningIntroAr: 'اسمع exchange فيه معلومة مش واضحة من أول مرة، ولاحظ إزاي الشخص يصلّحها بدل ما يخمّن.',
    listeningClips: [
      {
        id: 'a1-u1-l05-contact-repair',
        titleAr: 'اكتب الإيميل صح',
        subtitleAr: 'Salma بتدي بيانات تواصل وOmar يطلب spelling.',
        speakers: [{ speaker: 'Salma', voice: 'Aoede' }, { speaker: 'Omar', voice: 'Charon' }],
        turns: [
          { speaker: 'Omar', text: 'What’s your email address?', style: 'clear and helpful' },
          { speaker: 'Salma', text: 'It’s salma dot hassan at example dot com.', style: 'natural, clear but not overly slow' },
          { speaker: 'Omar', text: 'Sorry, how do you spell Hassan?', style: 'polite and careful' },
          { speaker: 'Salma', text: 'H-A-S-S-A-N.', style: 'clear, spelling each letter separately' },
          { speaker: 'Omar', text: 'Got it. Thank you.', style: 'relieved and friendly' },
        ],
        questions: [
          { id: 'repair-reason', promptAr: 'Omar طلب إيه بالظبط؟', options: ['رقم التليفون', 'تهجئة Hassan', 'عنوان البيت'], answerIndex: 1, feedbackAr: 'صح — ما خمّنش الاسم؛ طلب spelling.' },
          { id: 'hassan-spelling', promptAr: 'التهجئة الصحيحة كانت إيه؟', options: ['H-A-S-A-N', 'H-A-S-S-A-N', 'H-E-S-S-A-N'], answerIndex: 1, feedbackAr: 'صح — H-A-S-S-A-N.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l05',
    missionTitleAr: 'بدّل بيانات تواصل واطلب توضيح',
    missionSetupAr: 'هتبادل بيانات contact خيالية مع Otti. هو هيدي معلومة فيها جزء محتاج repair؛ مهمتك إنك ما تخمّنش وتطلب clarification مناسب.',
    missionUsefulLanguage: ['What’s your phone number?', 'What’s your email address?', 'How do you spell that?', 'Can you say that again?'],
    sourceNoteAr: 'A1 U1-L05: exchange contact details + genuine repair. الـrepair هو قلب المهمة، مش generic modal lesson.',
  },
  {
    id: 'a1-u1-l06',
    level: 'A1',
    unit: 1,
    lesson: 6,
    code: 'A1 • U1-L06',
    titleEn: 'This is my friend …',
    titleAr: 'قدّم شخص واتفاعل اجتماعيًا',
    estimatedMinutes: 10,
    goalAr: 'بعد الدرس ده هتقدر تقدّم شخص تاني، تتفاعل مع خبر بسيط كويس أو وحش، وتقفل اللقاء بطريقة اجتماعية طبيعية.',
    goalExample: ['This is my friend Lina.', 'Oh no. I’m sorry.'],
    prepIntroAr: 'الـphrase load هنا كبير، فهنجمعه في social routines بدل 12 mini-lessons: introduction، reaction، welcome، closing.',
    prepItems: [
      { id: 'this-is', english: 'This is my friend …', meaningAr: 'ده/دي صديقي/صديقتي …', exampleEn: 'This is my friend Lina.', role: 'use' },
      { id: 'guess-what', english: 'Guess what …', meaningAr: 'خمن / عارف إيه؟', exampleEn: 'Guess what — I have good news.', role: 'hear' },
      { id: 'good-news', english: 'good news', meaningAr: 'خبر كويس', exampleEn: 'I have good news.', role: 'hear' },
      { id: 'bad-news', english: 'bad news', meaningAr: 'خبر وحش', exampleEn: 'I have bad news.', role: 'hear' },
      { id: 'oh-no', english: 'Oh no!', meaningAr: 'أوه لا / يا نهار', exampleEn: 'Oh no! Is everything okay?', role: 'use' },
      { id: 'im-sorry', english: 'I’m sorry.', meaningAr: 'أنا آسف / متأسف لسماع كده', exampleEn: 'Oh no. I’m sorry.', role: 'use' },
      { id: 'really-good', english: 'really good', meaningAr: 'كويس جدًا', exampleEn: 'That’s really good.', role: 'use' },
      { id: 'welcome', english: 'Welcome to …', meaningAr: 'أهلاً بيك في …', exampleEn: 'Welcome to the class.', role: 'use' },
      { id: 'youre-welcome', english: 'You’re welcome.', meaningAr: 'العفو', exampleEn: 'Thank you. — You’re welcome.', role: 'hear' },
      { id: 'see-you', english: 'See you.', meaningAr: 'أشوفك بعدين', exampleEn: 'See you tomorrow.', role: 'use' },
    ],
    move: {
      eyebrowAr: 'Social move',
      titleAr: 'ردّك يتغيّر حسب الخبر',
      introAr: 'مش كل reaction تنفع لكل موقف. اسمع هل الخبر positive ولا negative وبعدين اختار رد بسيط مناسب.',
      steps: [
        { labelEn: 'Introduce', explanationAr: 'قدّم الشخص بجملة قصيرة.' },
        { labelEn: 'Listen', explanationAr: 'افهم هل الخبر كويس ولا وحش.' },
        { labelEn: 'React', explanationAr: 'اختار reaction مناسب بدل رد محفوظ لأي حاجة.' },
        { labelEn: 'Close', explanationAr: 'اقفل اللقاء بـSee you أو closing بسيط.' },
      ],
      example: [
        { speaker: 'A', text: 'This is my friend Lina.' },
        { speaker: 'B', text: 'Hi, Lina. Welcome to the class.' },
        { speaker: 'A', text: 'Bad news — her phone is broken.' },
        { speaker: 'B', text: 'Oh no. I’m sorry.' },
      ],
      noteAr: 'الهدف social routine كاملة، مش حفظ كل phrase في الـsource كعنصر مستقل.',
    },
    listeningIntroAr: 'اسمع لقاء اجتماعي صغير فيه introduction وخبر كويس وخبر وحش وclosing.',
    listeningClips: [
      {
        id: 'a1-u1-l06-social-reactions',
        titleAr: 'صديقة جديدة وخبرين',
        subtitleAr: 'Maya بتعرّف Omar على Lina.',
        speakers: [{ speaker: 'Maya', voice: 'Kore' }, { speaker: 'Omar', voice: 'Puck' }],
        turns: [
          { speaker: 'Maya', text: 'Hi, Omar. This is my friend Lina.', style: 'warm and social' },
          { speaker: 'Omar', text: 'Hi, Lina. Welcome to the class.', style: 'friendly and welcoming' },
          { speaker: 'Maya', text: 'Guess what — good news. Lina has a new job.', style: 'cheerful and excited' },
          { speaker: 'Omar', text: 'Oh yes? That’s really good!', style: 'genuinely pleased' },
          { speaker: 'Maya', text: 'But bad news — her phone is broken.', style: 'slightly disappointed' },
          { speaker: 'Omar', text: 'Oh no. I’m sorry.', style: 'sympathetic' },
          { speaker: 'Maya', text: 'It’s okay. See you tomorrow.', style: 'light and friendly' },
        ],
        questions: [
          { id: 'good-news-job', promptAr: 'إيه الـgood news؟', options: ['Lina عندها شغل جديد', 'التليفون اتصلح', 'Omar عنده شغل جديد'], answerIndex: 0, feedbackAr: 'صح — Lina has a new job.' },
          { id: 'oh-no-phone', promptAr: 'Omar قال “Oh no” على إيه؟', options: ['الشغل الجديد', 'التليفون المكسور', 'الـclass'], answerIndex: 1, feedbackAr: 'صح — reaction للخبر الوحش عن التليفون.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l06',
    missionTitleAr: 'لقاء اجتماعي قصير',
    missionSetupAr: 'Otti هيقدّم لك شخص بشكل بسيط ويشارك خبر كويس أو وحش. اتفاعل حسب المعنى، وخلّي اللقاء يقفل طبيعي. مش مطلوب تستخدم كل phrases.',
    missionUsefulLanguage: ['This is my friend …', 'Welcome to …', 'That’s really good.', 'Oh no.', 'I’m sorry.', 'See you.'],
    sourceNoteAr: 'A1 U1-L06: introduce another person + social reaction + closing. phrase density متجمعة في routines، مش mini-lessons.',
  },
  {
    id: 'a1-u1-l07',
    level: 'A1',
    unit: 1,
    lesson: 7,
    code: 'A1 • U1-L07',
    titleEn: 'Personal profile transfer',
    titleAr: 'اجمع البروفايل من محادثة حقيقية',
    estimatedMinutes: 11,
    goalAr: 'ده transfer lesson: مفيش grammar أو vocabulary جديدة. هتجمع معلومات ناقصة عن شخص جديد وتستخدمها في exchange مش محفوظ.',
    goalExample: ['Where do you live?', 'Sorry, how do you spell that?'],
    prepIntroAr: 'Quick recall فقط. كل اللي هنا اتعلمته قبل كده؛ الهدف تشوف هل تقدر تختار السؤال المناسب وقت ما تحتاجه.',
    prepItems: [
      { id: 'r-name', english: 'What’s your name?', meaningAr: 'الاسم', exampleEn: 'What’s your name?', role: 'use' },
      { id: 'r-age', english: 'How old are you?', meaningAr: 'العمر', exampleEn: 'How old are you?', role: 'use' },
      { id: 'r-origin', english: 'Where are you from?', meaningAr: 'الأصل', exampleEn: 'Where are you from?', role: 'use' },
      { id: 'r-live', english: 'Where do you live?', meaningAr: 'السكن', exampleEn: 'Where do you live?', role: 'use' },
      { id: 'r-work', english: 'What do you do?', meaningAr: 'الشغل/الدراسة', exampleEn: 'What do you do?', role: 'use' },
      { id: 'r-contact', english: 'What’s your email address?', meaningAr: 'بيانات التواصل', exampleEn: 'What’s your email address?', role: 'use' },
      { id: 'r-repair', english: 'How do you spell that?', meaningAr: 'إصلاح معلومة مش واضحة', exampleEn: 'Sorry, how do you spell that?', role: 'use' },
    ],
    move: {
      eyebrowAr: 'Transfer',
      titleAr: 'اسأل عن الناقص، مش كل حاجة بالترتيب',
      introAr: 'المحادثة الحقيقية مش form بيتقري من فوق لتحت. اسمع اللي اتقال واسأل فقط عن المعلومات اللي لسه ناقصة.',
      steps: [
        { labelEn: 'Notice', explanationAr: 'إيه اللي عرفته بالفعل؟' },
        { labelEn: 'Ask', explanationAr: 'اسأل عن معلومة ناقصة واحدة.' },
        { labelEn: 'Repair', explanationAr: 'لو detail مهمة مش واضحة، اطلب clarification.' },
        { labelEn: 'Use', explanationAr: 'استخدم معلومة من الشخص في رد أو summary قصير.' },
      ],
      example: [
        { speaker: 'A', text: 'I’m Sara. I’m from Jordan and I live in Cairo.' },
        { speaker: 'B', text: 'What do you do, Sara?' },
      ],
      noteAr: 'مفيش hidden new content هنا. لو Otti احتاج كلمة سياقية، يديها لك من غير ما تتحول لهدف جديد.',
    },
    listeningIntroAr: 'اسمع profile exchange متكامل. ركّز على إيه اتقال من نفسه وإيه احتاج سؤال أو repair.',
    listeningClips: [
      {
        id: 'a1-u1-l07-profile-transfer',
        titleAr: 'بروفايل جديد',
        subtitleAr: 'Adam بيجمع بيانات أساسية عن Sara.',
        speakers: [{ speaker: 'Adam', voice: 'Charon' }, { speaker: 'Sara', voice: 'Aoede' }],
        turns: [
          { speaker: 'Adam', text: 'Hi. What’s your name?', style: 'friendly and clear' },
          { speaker: 'Sara', text: 'I’m Sara Nabil. I’m twenty-four. I’m from Jordan, but I live in Cairo.', style: 'natural and unhurried' },
          { speaker: 'Adam', text: 'What do you do?', style: 'friendly' },
          { speaker: 'Sara', text: 'I work as a designer.', style: 'clear' },
          { speaker: 'Adam', text: 'And what’s your email address?', style: 'careful' },
          { speaker: 'Sara', text: 'sara dot nabil at example dot com.', style: 'natural, slightly faster than spelling pace' },
          { speaker: 'Adam', text: 'Sorry, how do you spell Nabil?', style: 'polite' },
          { speaker: 'Sara', text: 'N-A-B-I-L.', style: 'clear, spelling each letter separately' },
        ],
        questions: [
          { id: 'sara-live', promptAr: 'Sara عايشة فين؟', options: ['Jordan', 'Cairo', 'London'], answerIndex: 1, feedbackAr: 'صح — أصلها Jordan لكنها بتعيش في Cairo.' },
          { id: 'sara-job', promptAr: 'Sara بتشتغل إيه؟', options: ['designer', 'doctor', 'student'], answerIndex: 0, feedbackAr: 'صح — designer.' },
          { id: 'repair-nabil', promptAr: 'Adam عمل repair على إيه؟', options: ['العمر', 'Nabil', 'Cairo'], answerIndex: 1, feedbackAr: 'صح — طلب spelling للاسم.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u1-l07',
    missionTitleAr: 'كمّل بروفايل شخص جديد',
    missionSetupAr: 'Otti عنده profile جديد. اعرف الاسم، معلومة عن المكان، الشغل/الدراسة، وcontact detail واحدة. فيه فرصة repair واحدة. في الآخر استخدم معلومتين عرفتهُم.',
    missionUsefulLanguage: ['What’s your name?', 'Where are you from?', 'Where do you live?', 'What do you do?', 'Can you say that again?'],
    sourceNoteAr: 'A1 U1-L07 transfer: no hidden new system. obtain missing information → repair if needed → use the profile in an unscripted exchange.',
  },
  {
    id: 'a1-u2-l01',
    level: 'A1',
    unit: 2,
    lesson: 1,
    code: 'A1 • U2-L01',
    titleEn: "Who’s in your family?",
    titleAr: 'العيلة والناس القريبين منك',
    estimatedMinutes: 10,
    goalAr: 'بعد الدرس ده هتقدر تقول وتفهم معلومات بسيطة عن family وfriends باستخدام have got وpossessives من غير ما نحول 24 كلمة لقائمة حفظ.',
    goalExample: ['I’ve got one sister.', 'I live with my parents.'],
    prepIntroAr: 'هنركز على family core اللي يخليك تتكلم. العلاقات الأقل شيوعًا تقدر تقابلها كـrecognition بعدين.',
    prepItems: [
      { id: 'mother', english: 'mother / mum', meaningAr: 'الأم', exampleEn: 'My mother lives in Cairo.', role: 'use' },
      { id: 'father', english: 'father / dad', meaningAr: 'الأب', exampleEn: 'My father is a teacher.', role: 'use' },
      { id: 'sister', english: 'sister', meaningAr: 'أخت', exampleEn: 'I’ve got one sister.', role: 'use' },
      { id: 'brother', english: 'brother', meaningAr: 'أخ', exampleEn: 'My brother is a student.', role: 'use' },
      { id: 'parents', english: 'parents', meaningAr: 'الوالدان', exampleEn: 'I live with my parents.', role: 'use' },
      { id: 'family-member', english: 'family member', meaningAr: 'فرد من العيلة', exampleEn: 'She’s a family member.', role: 'hear' },
      { id: 'best-friend', english: 'best friend', meaningAr: 'أقرب صديق', exampleEn: 'Omar is my best friend.', role: 'use' },
      { id: 'have-got', english: 'I’ve got …', meaningAr: 'عندي …', exampleEn: 'I’ve got two brothers.', role: 'use' },
      { id: 'live-with', english: 'live with …', meaningAr: 'أعيش مع …', exampleEn: 'I live with my parents.', role: 'use' },
      { id: 'my-your', english: 'my / your / his / her', meaningAr: 'ملكية بسيطة', exampleEn: 'My sister. Her friend.', role: 'use' },
    ],
    move: {
      eyebrowAr: 'Small system',
      titleAr: 'relationship + have got + possessive',
      introAr: 'ثلاث أدوات صغيرة تكفيك تعمل family profile بسيط.',
      steps: [
        { labelEn: 'Have got', explanationAr: 'قول مين موجود في العيلة: I’ve got one sister.' },
        { labelEn: 'Possessive', explanationAr: 'اربط الشخص بصاحبه: my sister / her friend.' },
        { labelEn: 'Live with', explanationAr: 'لو السكن مهم: I live with my parents.' },
      ],
      example: [
        { speaker: 'A', text: 'Have you got any brothers or sisters?' },
        { speaker: 'B', text: 'I’ve got one sister. She’s a student.' },
      ],
      noteAr: 'get married وgrow up مش أهداف هنا؛ المنهج مأجلهم لسياق حياة/ماضي أنسب.',
      languageNote: [
        { form: 'my sister', explanationAr: 'الشخص يخصني/مرتبط بيا.' },
        { form: 'her brother', explanationAr: 'الـbrother مرتبط بـher.' },
      ],
    },
    listeningIntroAr: 'اسمع شخصين بيتكلموا عن family وناس قريبين، وامسك العلاقة والمعلومة الأساسية.',
    listeningClips: [
      {
        id: 'a1-u2-l01-family-chat',
        titleAr: 'مين في العيلة؟',
        subtitleAr: 'Sara و Omar بيتبادلوا معلومات بسيطة.',
        speakers: [{ speaker: 'Sara', voice: 'Kore' }, { speaker: 'Omar', voice: 'Puck' }],
        turns: [
          { speaker: 'Sara', text: 'Have you got any brothers or sisters?', style: 'friendly and clear' },
          { speaker: 'Omar', text: 'I’ve got one sister. Her name is Lina. I live with my parents.', style: 'relaxed and clear' },
          { speaker: 'Sara', text: 'Is Lina a student?', style: 'interested' },
          { speaker: 'Omar', text: 'Yes. And my best friend Karim lives near us.', style: 'friendly' },
          { speaker: 'Sara', text: 'Nice. I live with my mother.', style: 'warm and natural' },
        ],
        questions: [
          { id: 'omar-sibling', promptAr: 'Omar عنده مين؟', options: ['أخت واحدة', 'أخين', 'مفيش إخوات'], answerIndex: 0, feedbackAr: 'صح — عنده sister واحدة اسمها Lina.' },
          { id: 'omar-lives', promptAr: 'Omar عايش مع مين؟', options: ['best friend', 'parents', 'sister فقط'], answerIndex: 1, feedbackAr: 'صح — “I live with my parents.”' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u2-l01',
    missionTitleAr: 'اتكلم عن family أو ناس قريبين',
    missionSetupAr: 'اتكلم عن عيلتك الحقيقية أو family خيالية لو تحب. شارك كام علاقة بسيطة واسأل Otti عن عيلته/أصحابه.',
    missionUsefulLanguage: ['I’ve got …', 'my sister / my brother', 'I live with …', 'best friend', 'Have you got … ?'],
    sourceNoteAr: 'A1 U2-L01: family/familiar-person information. active core + supported recognition؛ مش 24-word chapter.',
  },
  {
    id: 'a1-u2-l02',
    level: 'A1',
    unit: 2,
    lesson: 2,
    code: 'A1 • U2-L02',
    titleEn: 'Which person is it?',
    titleAr: 'اسمع الوصف وحدد الشخص',
    estimatedMinutes: 9,
    goalAr: 'ده درس receptive أساسًا: بعده هتقدر تسمع وصف قصير لشخص وتحدد مين المقصود من clues زي family/job/age/appearance.',
    goalExample: ['The tall man with glasses.', 'That’s Omar.'],
    prepIntroAr: 'هنا مش هنحوّل الوصف لمهمة كلام كبيرة. الكلمات دي أساسًا هتساعدك تفهم الوصف وتتعرف على الشخص.',
    prepItems: [
      { id: 'look-like', english: 'look like', meaningAr: 'شكله/تشبه', exampleEn: 'What does he look like?', role: 'hear' },
      { id: 'tall', english: 'tall', meaningAr: 'طويل', exampleEn: 'He’s tall.', role: 'hear' },
      { id: 'short', english: 'short', meaningAr: 'قصير', exampleEn: 'She’s short.', role: 'hear' },
      { id: 'young', english: 'young', meaningAr: 'صغير السن', exampleEn: 'He’s young.', role: 'hear' },
      { id: 'old', english: 'old', meaningAr: 'كبير السن / قديم حسب السياق', exampleEn: 'He’s an older man.', role: 'hear' },
      { id: 'long-hair', english: 'long hair', meaningAr: 'شعر طويل', exampleEn: 'She has long hair.', role: 'hear' },
      { id: 'short-hair', english: 'short hair', meaningAr: 'شعر قصير', exampleEn: 'He has short hair.', role: 'hear' },
      { id: 'glasses', english: 'glasses', meaningAr: 'نظارة', exampleEn: 'He has glasses.', role: 'hear' },
      { id: 'which-person', english: 'Which person is it?', meaningAr: 'أنهي شخص؟', exampleEn: 'Which person is it?', role: 'use' },
    ],
    move: {
      eyebrowAr: 'Listening strategy',
      titleAr: 'اجمع 2–3 clues قبل ما تختار',
      introAr: 'مش لازم تفهم كل كلمة. relation + job/age + appearance غالبًا يكفوا يحددوا الشخص.',
      steps: [
        { labelEn: 'Who?', explanationAr: 'هل قال sister / friend / teacher مثلًا؟' },
        { labelEn: 'Basic fact', explanationAr: 'العمر أو الشغل ممكن يقلل الاختيارات.' },
        { labelEn: 'Appearance', explanationAr: 'tall / glasses / hair تساعدك تأكد الاختيار.' },
      ],
      example: [
        { speaker: 'A', text: 'My brother is thirty. He’s a driver. He’s tall and he has glasses.' },
        { speaker: 'B', text: 'The tall man with glasses?' },
      ],
      noteAr: 'نجاح الدرس إنك تحدد الشخص من الوصف. مش مطلوب تنتج كل adjectives بنفسك.',
    },
    listeningIntroAr: 'اسمع وصفين قصيرين. جاوب من الـclues؛ مش لازم تحفظ الوصف كلمة بكلمة.',
    listeningClips: [
      {
        id: 'a1-u2-l02-identify-person',
        titleAr: 'مين الشخص؟',
        subtitleAr: 'Omar بيوصف أخوه وصديقته.',
        speakers: [{ speaker: 'Maya', voice: 'Aoede' }, { speaker: 'Omar', voice: 'Charon' }],
        turns: [
          { speaker: 'Maya', text: 'Which person is your brother?', style: 'curious and clear' },
          { speaker: 'Omar', text: 'He’s thirty and he works as a driver. He’s tall and he has glasses.', style: 'clear and unhurried' },
          { speaker: 'Maya', text: 'Okay. And your friend Lina?', style: 'friendly' },
          { speaker: 'Omar', text: 'Lina is twenty-two. She’s a student. She’s short and she has long hair.', style: 'clear and conversational' },
        ],
        questions: [
          { id: 'brother-description', promptAr: 'أنهي وصف لأخو Omar؟', options: ['tall + glasses + driver', 'short + long hair + student', 'young + teacher'], answerIndex: 0, feedbackAr: 'صح — tall، glasses، وdriver.' },
          { id: 'lina-description', promptAr: 'أنهي وصف لـLina؟', options: ['30 + driver', '22 + student + long hair', 'teacher + glasses'], answerIndex: 1, feedbackAr: 'صح — 22، student، وlong hair.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u2-l02',
    missionTitleAr: 'خمن الشخص من الوصف',
    missionSetupAr: 'Roster: Maya — 24, teacher, long hair • Omar — 30, driver, glasses • Lina — 22, student, short hair. Otti هيوصف شخص من غير ما يقول اسمه؛ إنت حدده. التركيز على الفهم، مش إنتاج الوصف.',
    missionUsefulLanguage: ['Maya / Omar / Lina', 'Can you say that again?', 'I think it’s …', 'The person with …'],
    sourceNoteAr: 'A1 U2-L02 يحافظ على C08 receptive: identify from a short description. production support ما يستبدلش comprehension evidence.',
  },
  {
    id: 'a1-u2-l03',
    level: 'A1',
    unit: 2,
    lesson: 3,
    code: 'A1 • U2-L03',
    titleEn: 'Tell me about this person',
    titleAr: 'اسأل عن شخص واربط معلومتين',
    estimatedMinutes: 10,
    goalAr: 'بعد الدرس ده هتقدر تسأل عن معلومات ناقصة عن شخص مألوف وتربط إجابتين قصيرتين بـand / but / or بدل ما تفضل كل معلومة لوحدها.',
    goalExample: ['She’s 25 and she lives in Alexandria.', 'He’s a student, but he works at the weekend.'],
    prepIntroAr: 'معظم لغة الـprofile اتعلمتها في Unit 1. الجديد الحقيقي هنا هو استعمالها عن شخص تالت وربط فكرتين بسيطتين.',
    prepItems: [
      { id: 'his-name', english: 'What’s his name?', meaningAr: 'اسمه إيه؟', exampleEn: 'What’s his name?', role: 'use' },
      { id: 'her-name', english: 'What’s her name?', meaningAr: 'اسمها إيه؟', exampleEn: 'What’s her name?', role: 'use' },
      { id: 'how-old-third', english: 'How old is he / she?', meaningAr: 'عنده/عندها كام سنة؟', exampleEn: 'How old is she?', role: 'use' },
      { id: 'where-live-third', english: 'Where does he / she live?', meaningAr: 'ساكن/ساكنة فين؟', exampleEn: 'Where does he live?', role: 'use' },
      { id: 'what-do-third', english: 'What does he / she do?', meaningAr: 'بيشتغل/بتشتغل إيه؟', exampleEn: 'What does she do?', role: 'use' },
      { id: 'and', english: 'and', meaningAr: 'و', exampleEn: 'She’s 25 and she lives in Cairo.', role: 'use' },
      { id: 'but', english: 'but', meaningAr: 'لكن', exampleEn: 'He’s a student, but he works at the weekend.', role: 'use' },
      { id: 'or', english: 'or', meaningAr: 'أو', exampleEn: 'Is she a teacher or a student?', role: 'use' },
      { id: 'he-she', english: 'he / she', meaningAr: 'هو / هي', exampleEn: 'He lives in Giza. She works in Cairo.', role: 'use' },
    ],
    move: {
      eyebrowAr: 'Information gap',
      titleAr: 'اسأل عن الناقص وبعدين اربط',
      introAr: 'بدل ما تكرر profile جاهز، خليك عندك سبب حقيقي للسؤال: فيه معلومة ناقصة عندك.',
      steps: [
        { labelEn: 'Ask', explanationAr: 'اسأل سؤال profile واحد عن الشخص.' },
        { labelEn: 'Listen', explanationAr: 'خد الإجابة وخزنها بدل ما تسأل نفس الحاجة.' },
        { labelEn: 'Connect', explanationAr: 'لما عندك معلومتين، اربطهم بـand أو but أو اختار بـor.' },
      ],
      example: [
        { speaker: 'A', text: 'What does Maya do?' },
        { speaker: 'B', text: 'She’s a teacher.' },
        { speaker: 'A', text: 'Where does she live?' },
        { speaker: 'B', text: 'She lives in Alexandria.' },
        { speaker: 'A', text: 'So, she’s a teacher and she lives in Alexandria.' },
      ],
      noteAr: 'الـ24 words في الـsource تفضل داخل mystery-person/profile interaction، مش chapter مفردات جديد.',
      languageNote: [
        { form: 'and', explanationAr: 'يجمع معلومتين متوافقين.' },
        { form: 'but', explanationAr: 'يربط فكرتين بينهم contrast بسيط.' },
        { form: 'or', explanationAr: 'يقدم اختيار بسيط.' },
      ],
    },
    listeningIntroAr: 'اسمع حوار فيه معلومات ناقصة عن شخص، ولاحظ السؤال ثم ربط المعلومات في الآخر.',
    listeningClips: [
      {
        id: 'a1-u2-l03-person-gap',
        titleAr: 'Tell me about Maya',
        subtitleAr: 'Karim بيسأل Sara عن صديقتها.',
        speakers: [{ speaker: 'Karim', voice: 'Puck' }, { speaker: 'Sara', voice: 'Kore' }],
        turns: [
          { speaker: 'Karim', text: 'Tell me about your friend Maya. How old is she?', style: 'friendly and curious' },
          { speaker: 'Sara', text: 'She’s twenty-five and she lives in Alexandria.', style: 'clear and natural' },
          { speaker: 'Karim', text: 'What does she do?', style: 'curious' },
          { speaker: 'Sara', text: 'She’s a teacher, but she studies English at night.', style: 'clear and conversational' },
          { speaker: 'Karim', text: 'Is she your sister or your friend?', style: 'light and curious' },
          { speaker: 'Sara', text: 'My friend.', style: 'friendly' },
        ],
        questions: [
          { id: 'maya-profile', promptAr: 'أنهي summary صح عن Maya؟', options: ['25 + Alexandria + teacher', '30 + Cairo + driver', '22 + student + Dubai'], answerIndex: 0, feedbackAr: 'صح — 25، Alexandria، teacher.' },
          { id: 'maya-relation', promptAr: 'Maya مين بالنسبة لـSara؟', options: ['sister', 'friend', 'mother'], answerIndex: 1, feedbackAr: 'صح — Maya صديقتها.' },
        ],
      },
    ],
    missionScenarioId: 'learn-v2-a1-u2-l03',
    missionTitleAr: 'اكتشف الـmystery profile',
    missionSetupAr: 'Otti عنده profile مخفي لشخص. اسأل 3 أسئلة مختلفة على الأقل عشان تعرفه، وبعدها لخّص معلومتين بجملة قصيرة باستخدام and أو but لو مناسب.',
    missionUsefulLanguage: ['What’s his/her name?', 'How old is he/she?', 'Where does he/she live?', 'What does he/she do?', 'and / but / or'],
    sourceNoteAr: 'A1 U2-L03: genuine information gap + simple cohesion. general and/but/or established هنا قبل transfer اللاحق.',
  },
];
