import type { SceneLessonDefinition } from '../types';

export const B1_U1_L02_SCENE_LESSON: SceneLessonDefinition = {
  id: 'b1-u1-l02-keep-conversation-going',
  levelId: 'b1',
  unitId: 'b1-u1-independent-conversation',
  unitTitle: 'From Routine Exchange to Independent Conversation',
  order: 2,
  title: 'Keep a Familiar Conversation Going',
  subtitle: 'Listen actively, pick up a useful detail, follow up, and manage several turns without waiting for a script.',
  performance: 'Sustain a fresh familiar conversation for several turns through acknowledgement, relevant follow-up, and simple turn management without being given the next question.',
  coreLanguage: [
    'get to know sb',
    'in touch',
    'you see',
    'bounded formal invitation language such as Would you like to …? / I’d like to invite you to …',
    'context vocabulary: agreement, conclude, encourage, reject, wonder',
    'integrated support only: emphatic do, let me for focus/turn-holding, negative tag questions, speech-act verbs',
    'connected-speech perception and production support; intelligibility over accent imitation',
  ],
  boundaries: [
    'The primary success condition is interactional continuity, not displaying every phrase, word, or grammar row.',
    'Do not turn the lesson into a four-rule grammar chapter. The grammar rows are integrated support for real turns.',
    'Teach get to know, in touch, and you see as usable formulaic resources in context, not as isolated translation items.',
    'agreement, conclude, encourage, reject, and wonder are productive contextual vocabulary, but they should be grouped around meaningful familiar situations rather than taught as a random list.',
    'The learner must generate relevant follow-up; a teacher-supplied next question does not count as independent evidence.',
    'Keep everyday conversation understandable and avoid very idiomatic usage.',
    'The final transfer must change the details/topic and reduce support.',
  ],
  source: {
    repository: 'addvaluewithai-hub/english-course',
    branch: '801114fdd860e8b9c1e7b137a0af1c3b3cc0e9cb',
    path: 'curriculum/levels/b1/design-review/07-lesson-briefs/lesson-briefs.md#u1-l02--keep-a-familiar-conversation-going',
    sourceLessonId: 'U1-L02',
  },
  scenes: [
    {
      id: 'maintain-conversation-diagnostic',
      title: 'Keep a familiar topic alive',
      goal: 'The learner can listen to a familiar update, pick up a relevant detail, and sustain the exchange for several turns without waiting for a supplied next question.',
      teaching: {
        explainInArabic: ['ابدأ باختبار خفيف: هقول update عادي، وإنت اسمع وامسك تفصيلة وابنِ عليها بدل سؤال محفوظ.'],
        englishTargets: ['acknowledge', 'pick a detail', 'relevant follow-up'],
        constraints: [
          'Do not model a full response before the first attempt.',
          'Let the exchange run for at least three learner turns when possible.',
          'Use this as diagnostic evidence; later scenes teach the language resources.',
        ],
      },
      board: {
        type: 'steps',
        title: 'Keep the turn alive',
        items: [
          { title: 'React', body: 'show you heard me' },
          { title: 'Pick', body: 'use one detail I gave you' },
          { title: 'Continue', body: 'ask or add something connected' },
        ],
      },
      interaction: {
        kind: 'guided_dialogue',
        setup: 'Give a familiar one-line update, answer the learner’s follow-up with one new detail, and see whether they can keep building for several turns.',
        learnerTask: 'Keep this conversation going naturally from what I tell you.',
        supportLadder: ['قل بالعربي: امسك تفصيلة من آخر جملة.', 'Name the useful detail only.', 'Give a question starter only, then change the detail for a fresh retry.'],
      },
    },
    {
      id: 'get-to-know-teach-use',
      title: 'Talk about a relationship developing with get to know',
      goal: 'The learner can understand and independently use get to know when talking about gradually becoming familiar with a person.',
      teaching: {
        explainInArabic: ['قدّم get to know لما بنتعرف على حد تدريجيًا، وبعدها اختبرها في شخص وسياق مختلف.'],
        englishTargets: ['I got to know her at work.', 'I want to get to know them better.'],
        constraints: [
          'Do not turn this into a tense lesson.',
          'Immediate repetition after a model is practice only.',
          'Use a fresh person/context before completing.',
        ],
      },
      board: { type: 'examples', title: 'A relationship develops', items: [{ title: 'get to know', body: 'become familiar with someone over time' }] },
      interaction: {
        kind: 'micro_practice',
        setup: 'Use one supported situation about meeting someone over time, then a changed situation with less support.',
        learnerTask: 'Use get to know naturally in the situation.',
        supportLadder: ['Explain the meaning in Arabic.', 'Give get to know only.', 'Model once, then change person and context.'],
      },
    },
    {
      id: 'in-touch-teach-use',
      title: 'Talk about continuing contact with in touch',
      goal: 'The learner can understand and independently use in touch when people continue communicating after they are apart.',
      teaching: {
        explainInArabic: ['قدّم in touch كفكرة استمرار التواصل حتى لو الناس مش بيشوفوا بعض كتير.'],
        englishTargets: ['We still keep in touch.', 'Are you still in touch with him?'],
        constraints: [
          'Do not expand into a collocation list.',
          'Create a second changed contact situation before deciding mastery.',
          'Accept natural equivalent grammar around the target phrase.',
        ],
      },
      board: { type: 'examples', title: 'Contact continues', items: [{ title: 'keep / be in touch', body: 'continue communicating' }] },
      interaction: {
        kind: 'micro_practice',
        setup: 'Use two different contexts such as an old classmate and a former colleague.',
        learnerTask: 'Say or ask naturally whether the people still communicate.',
        supportLadder: ['Give the meaning in Arabic.', 'Show in touch without the full sentence.', 'Model one example, then change the people.'],
      },
    },
    {
      id: 'you-see-teach-use',
      title: 'Use you see to add a useful explanation',
      goal: 'The learner can understand and use you see as a simple signal that an explanation or background detail is coming.',
      teaching: {
        explainInArabic: ['قدّم you see كإشارة قصيرة قبل explanation مفيدة، مش filler نحطها في كل جملة.'],
        englishTargets: ['You see, I was new there.'],
        constraints: [
          'Do not encourage overuse.',
          'Require the learner to finish a meaningful explanation after the phrase.',
          'Use a fresh reason/background context after any model.',
        ],
      },
      board: { type: 'examples', title: 'Add the explanation', items: [{ title: 'You see, …', body: 'here is the background/reason' }] },
      interaction: {
        kind: 'micro_practice',
        setup: 'Give a situation where the learner needs to explain why something happened or why they reacted that way. Then change the reason.',
        learnerTask: 'Use you see and finish the explanation in your own words.',
        supportLadder: ['Say in Arabic: ابدأ explanation.', 'Give You see… only.', 'Model once, then change the reason.'],
      },
    },
    {
      id: 'continuation-phrase-retrieval',
      title: 'Retrieve an earlier conversation link without a cue',
      goal: 'The learner can retrieve get to know, in touch, or you see after a gap when the conversation naturally needs one of them.',
      teaching: {
        explainInArabic: ['ما تقولش إن دي مراجعة. افتح موقفين مختلفين وخلي الـphrase المناسبة تطلع من المعنى.'],
        englishTargets: ['get to know', 'in touch', 'you see'],
        constraints: [
          'Do not name the target before the attempt.',
          'Test two different earlier phrases in changed contexts.',
          'If one fails, repair and use a fresh context before completing.',
        ],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Create two natural mini-situations selected from relationship development, continued contact, and adding an explanation.',
        learnerTask: 'Respond naturally to each situation.',
        supportLadder: ['Give only the meaning/function.', 'Give a light first-word or phrase-shape cue.', 'Reveal the phrase, then change context for a fresh retry.'],
      },
    },
    {
      id: 'wonder-teach-use',
      title: 'Raise an idea or uncertainty with wonder',
      goal: 'The learner can understand and use wonder naturally to raise a thought, possibility, or polite question inside familiar planning talk.',
      teaching: {
        explainInArabic: ['قدّم I wonder… كطريقة ترفع فكرة أو سؤال بهدوء جوه planning أو discussion.'],
        englishTargets: ['I wonder if Saturday is better.'],
        constraints: [
          'Keep the pattern bounded and useful.',
          'Do not teach a broad complement grammar lesson.',
          'Use two different planning questions before completing when practical.',
        ],
      },
      board: { type: 'examples', title: 'Raise a thought', items: [{ title: 'I wonder if …', body: 'introduce a possibility/question' }] },
      interaction: {
        kind: 'micro_practice',
        setup: 'Give two ordinary planning decisions and ask the learner to raise one possible question or alternative with wonder.',
        learnerTask: 'Use wonder to raise the idea naturally.',
        supportLadder: ['Explain the communicative job in Arabic.', 'Give I wonder if… only.', 'Model once, then change the planning detail.'],
      },
    },
    {
      id: 'encourage-teach-use',
      title: 'Use encourage inside a real situation',
      goal: 'The learner can understand and use encourage to describe helping or persuading someone to do something positive.',
      teaching: {
        explainInArabic: ['قدّم encourage من خلال شخص شجع شخص تاني يعمل حاجة أو يكمل فيها.'],
        englishTargets: ['She encouraged me to join.'],
        constraints: ['Keep the situation concrete.', 'Do not teach verb-complement theory.', 'Use a changed person/action for independent use.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Give one supported example, then ask about a new situation where someone helped another person feel able or willing to act.',
        learnerTask: 'Describe what the person did using encourage.',
        supportLadder: ['Give the meaning in Arabic.', 'Give encouraged only.', 'Model one sentence, then change the action.'],
      },
    },
    {
      id: 'reject-teach-use',
      title: 'Use reject for an idea or proposal that is not accepted',
      goal: 'The learner can understand and use reject in a familiar planning/decision context where an idea, proposal, or option is not accepted.',
      teaching: {
        explainInArabic: ['قدّم reject لما فكرة أو proposal تتعرض وتتقال لأ، وبعدها استخدم موقف جديد.'],
        englishTargets: ['They rejected the first idea.'],
        constraints: ['Keep it about ideas/proposals/options here.', 'Do not open a synonyms list.', 'Use a fresh option for independent use.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Offer two possible plans and describe that the group did not accept one. Then change the plan and ask the learner to report what happened.',
        learnerTask: 'Say what happened to the idea using reject.',
        supportLadder: ['Explain the meaning in Arabic.', 'Give rejected only.', 'Model once, then change the proposal.'],
      },
    },
    {
      id: 'agreement-teach-use',
      title: 'Name the shared decision with agreement',
      goal: 'The learner can understand and use agreement when people reach the same accepted decision or arrangement.',
      teaching: {
        explainInArabic: ['قدّم agreement كالحالة أو النتيجة لما الناس تتفق على قرار أو ترتيب.'],
        englishTargets: ['We finally reached an agreement.'],
        constraints: ['Keep the context familiar.', 'Do not require a dictionary definition.', 'Use a second changed decision context before completing.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Run a tiny choice between options until both sides accept one, then later use a new choice.',
        learnerTask: 'Describe the result using agreement.',
        supportLadder: ['Say in Arabic: وصلنا لاتفاق.', 'Give agreement only.', 'Model once, then change the decision.'],
      },
    },
    {
      id: 'conclude-teach-use',
      title: 'State what you finally concluded',
      goal: 'The learner can understand and use conclude to state a final judgement or result reached after considering information.',
      teaching: {
        explainInArabic: ['وضح إن conclude هنا معناها نوصل لاستنتاج أو نتيجة بعد ما فكرنا في المعلومات.'],
        englishTargets: ['We concluded that the smaller group worked better.'],
        constraints: ['Do not confuse this with concrete.', 'Keep the sentence simple.', 'Use a fresh set of facts for independent use.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Give two or three simple facts about a familiar plan or activity and ask what the group concluded. Then change the facts.',
        learnerTask: 'State the conclusion naturally using conclude.',
        supportLadder: ['Explain the difference from concrete if needed.', 'Give We concluded that… only.', 'Model once, then use new facts.'],
      },
    },
    {
      id: 'planning-vocabulary-integration',
      title: 'Use the decision words across one real planning exchange',
      goal: 'The learner can use wonder, encourage, reject, agreement, and conclude across a compact multi-turn planning situation when each meaning becomes relevant.',
      teaching: {
        explainInArabic: ['اعمل planning حقيقية صغيرة بدل vocab quiz: فكرة تتطرح، حد يشجع، فكرة تترفض، نوصل لاتفاق، وفي الآخر نستنتج حاجة.'],
        englishTargets: ['wonder', 'encourage', 'reject', 'agreement', 'conclude'],
        constraints: [
          'Do not ask for five dictionary definitions.',
          'Create separate natural opportunities across several turns; the learner does not need all five in one sentence.',
          'Do not complete after only one or two words: the scene explicitly integrates all five productive contextual words.',
          'If a word needed answer-bearing help, create another small changed opportunity for that word before judging it secure.',
        ],
      },
      board: {
        type: 'steps',
        title: 'A decision develops',
        items: [
          { title: 'wonder', body: 'raise an idea/question' },
          { title: 'encourage / reject', body: 'respond to ideas/actions' },
          { title: 'agreement', body: 'reach a shared decision' },
          { title: 'conclude', body: 'state the final result/judgement' },
        ],
      },
      interaction: {
        kind: 'guided_dialogue',
        setup: 'Run a compact group-plan simulation with changing details. Engineer natural moments for all five words across multiple turns.',
        learnerTask: 'Help make the plan and talk through what happens at each stage.',
        teacherMoves: [
          'Invite the learner to wonder about one detail.',
          'Introduce one person/action that can be encouraged.',
          'Offer one proposal that can naturally be rejected.',
          'Negotiate until an agreement is reached.',
          'At the end ask what the group concluded from the discussion.',
        ],
        supportLadder: ['Point only to the communicative stage.', 'Offer the target word without a full sentence.', 'Model one sentence, then change that detail before the retry.'],
      },
    },
    {
      id: 'emphatic-do-support',
      title: 'Use emphatic do when real emphasis helps the turn',
      goal: 'The learner can recognise and selectively use emphatic do to strengthen a genuine positive statement such as a preference or agreement.',
      teaching: {
        explainInArabic: ['قدّم I do like… كـtool للتأكيد لما المعنى محتاج emphasis، مش قاعدة لازم تدخل في كل جملة.'],
        englishTargets: ['I do like the idea.'],
        constraints: ['Integrated support only.', 'Do not teach a broad auxiliary-do chapter.', 'Use a real contrast/disagreement context.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Create one situation where someone doubts the learner likes/agrees with something, then a changed situation where emphasis is useful.',
        learnerTask: 'Respond with natural emphasis if it helps.',
        supportLadder: ['Name the function: emphasise.', 'Give I do… as a starter.', 'Model once, then change the preference.'],
      },
    },
    {
      id: 'let-me-support',
      title: 'Hold the turn naturally with Let me',
      goal: 'The learner can use Let me… to buy a moment, focus, or organise a response during live conversation.',
      teaching: {
        explainInArabic: ['قدّم Let me think / Let me see كطريقة طبيعية تاخد لحظة من غير ما تسيب الـturn.'],
        englishTargets: ['Let me think for a second.', 'Let me see.'],
        constraints: ['Integrated support only.', 'Do not force the phrase when the learner already answers immediately.', 'Use a question that genuinely benefits from thinking time.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Ask a familiar choice/question that takes a little thought, then later another different one.',
        learnerTask: 'Hold the turn naturally while you think, then answer.',
        supportLadder: ['Explain in Arabic that they can keep the turn while thinking.', 'Give Let me… only.', 'Model one chunk, then ask a new question.'],
      },
    },
    {
      id: 'negative-tag-support',
      title: 'Use a simple negative tag to check a shared fact',
      goal: 'The learner can recognise and selectively use a simple negative tag question to check a familiar shared fact.',
      teaching: {
        explainInArabic: ['قدّم مثال واحد bounded زي You know Sam, don’t you? كطريقة check، من غير نظام tag questions كامل.'],
        englishTargets: ['You know Sam, don’t you?'],
        constraints: ['Integrated support only.', 'Do not teach the full tag-question paradigm.', 'Accept a simple equivalent check if the intended interaction is clear, while encouraging the target once.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Create one clear shared-fact context, then another with a different person/activity.',
        learnerTask: 'Check the shared fact naturally.',
        supportLadder: ['Name the function: check/confirm.', 'Give the main clause and let the learner finish the tag.', 'Model once, then change the fact.'],
      },
    },
    {
      id: 'speech-act-verb-support',
      title: 'State the conversational act clearly',
      goal: 'The learner can use a simple speech-act verb such as suggest or promise when it naturally clarifies what they are doing in the conversation.',
      teaching: {
        explainInArabic: ['قدّم I suggest… وI promise… كأمثلة صغيرة إنك ممكن تسمي الفعل اللي بتعمله في الكلام.'],
        englishTargets: ['I suggest Saturday.', 'I promise I’ll call.'],
        constraints: ['Integrated support only.', 'Do not teach an exhaustive speech-act vocabulary list.', 'Use two different functions: one suggestion and one promise.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Give one planning moment requiring a suggestion and one social follow-up requiring a promise.',
        learnerTask: 'Make the conversational act clear in a short natural turn.',
        supportLadder: ['Name the function only: suggest or promise.', 'Give I suggest… / I promise… starters.', 'Model once, then change the content.'],
      },
    },
    {
      id: 'connected-speech-support',
      title: 'Follow and produce useful chunks in connected speech',
      goal: 'The learner can recognise earlier lesson chunks in clear connected speech and produce them intelligibly without accent imitation.',
      teaching: {
        explainInArabic: ['الهدف إنك تسمع الـchunk كوحدة وتقولها بشكل مفهوم، مش تقلد accent.'],
        englishTargets: ['get to know', 'keep in touch', 'I wonder if…', 'Would you like to…?'],
        constraints: [
          'Do not claim precise pronunciation scoring.',
          'Focus on intelligibility and chunk recognition.',
          'Use earlier lesson language rather than introducing new pronunciation content.',
        ],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Say several earlier chunks in short natural sentences at clear B1 speed, check recognition, then let the learner use two of them in short meaningful turns.',
        learnerTask: 'Identify the chunk you heard and use selected chunks clearly enough to be understood.',
        supportLadder: ['Repeat the full phrase more slowly.', 'Isolate the chunk once.', 'Return immediately to a fresh full sentence.'],
      },
    },
    {
      id: 'formal-invitation-accepted',
      title: 'Make a polite invitation and continue after acceptance',
      goal: 'The learner can make a bounded formal/polite invitation and continue naturally when the partner accepts.',
      teaching: {
        explainInArabic: ['قدّم الدعوة المهذبة كحركة صغيرة جوه conversation، وبعد القبول لازم الكلام يكمل طبيعي.'],
        englishTargets: ['Would you like to join us on Friday?', 'I’d like to invite you to the event.'],
        constraints: ['No business-protocol lesson.', 'Accept equivalent polite wording.', 'Do not complete immediately after the invitation; continue after acceptance.'],
      },
      board: {
        type: 'steps',
        title: 'Invite, then keep talking',
        items: [
          { title: 'Invite', body: 'Would you like to …?' },
          { title: 'Partner accepts', body: 'Great / yes' },
          { title: 'Continue', body: 'time · place · next detail' },
        ],
      },
      interaction: {
        kind: 'guided_dialogue',
        setup: 'Create a familiar club/course/social event. Let the learner invite you politely; accept and continue with a realistic detail question.',
        learnerTask: 'Invite me politely and keep the exchange going after I accept.',
        supportLadder: ['Give only the event and invitation function.', 'Offer Would you like to… as starter.', 'Model once, then change the event before retrying.'],
      },
    },
    {
      id: 'formal-invitation-declined',
      title: 'Keep the conversation natural when an invitation is declined',
      goal: 'The learner can make another polite invitation in a fresh context and respond naturally when the partner declines or is unsure.',
      teaching: {
        explainInArabic: ['هنا غير السياق. نفس القدرة بس المرة دي الرد مش yes، والمطلوب ما تقفلش الكلام بشكل آلي.'],
        englishTargets: ['polite invitation', 'natural response to no / maybe', 'relevant next move'],
        constraints: [
          'Use a different event from the accepted-invitation scene.',
          'Do not tell the learner in advance whether the partner will decline or hesitate.',
          'Judge both the invitation and the continuation after the response.',
        ],
      },
      interaction: {
        kind: 'guided_dialogue',
        setup: 'Create a fresh event. Let the learner invite you, then decline politely or say maybe and give one reason.',
        learnerTask: 'Invite me and respond naturally to whatever answer I give.',
        supportLadder: ['Give the invitation function only.', 'Give a short Arabic cue for reacting to the answer.', 'If you model a response, change the event and partner answer for the retry.'],
      },
    },
    {
      id: 'follow-everyday-conversation',
      title: 'Follow the thread of an everyday conversation',
      goal: 'The learner can follow most of a short everyday conversation when the language is familiar and not highly idiomatic, identifying how the topic develops.',
      teaching: {
        explainInArabic: ['قول إن مش لازم تمسك كل كلمة؛ ركز مين بيقول إيه وإزاي الموضوع بيتحرك من نقطة لنقطة.'],
        englishTargets: ['short everyday conversation', 'main topic', 'one changed detail', 'speaker intention'],
        constraints: ['This is receptive ability evidence.', 'Do not require verbatim recall.', 'Use a fresh multi-turn spoken mini-dialogue without transcript.'],
      },
      interaction: {
        kind: 'micro_practice',
        setup: 'Perform a short multi-turn everyday dialogue between two people using familiar content and a small change of plan. Ask for the main topic and what changed.',
        learnerTask: 'Tell me what the conversation was mainly about and what changed.',
        supportLadder: ['Replay the whole mini-dialogue once.', 'Give topic/change categories as choices.', 'Explain one missed point, then use a fresh shorter dialogue.'],
      },
    },
    {
      id: 'mixed-surprise-retrieval',
      title: 'Recover earlier language after a longer gap',
      goal: 'The learner can retrieve earlier phrases, vocabulary, or support patterns in new conversational needs without being told what to use.',
      teaching: {
        explainInArabic: ['ما تعلنش quiz. افتح 3 turns طبيعيين كل واحد فيهم محتاج حاجة من أول الدرس بشكل مختلف.'],
        englishTargets: ['one earlier phrase', 'one planning word', 'one support pattern'],
        constraints: [
          'Do not name the exact target before the attempt.',
          'Choose items that have not appeared in the immediately previous scene.',
          'Use at least three different retrieval needs across a natural exchange.',
          'If retrieval fails after support, create a changed retry before completing.',
        ],
      },
      interaction: {
        kind: 'guided_dialogue',
        setup: 'Run a short conversation that naturally creates three retrieval opportunities: a relationship/contact/explanation phrase, one decision word, and one grammar/turn-management support pattern.',
        learnerTask: 'Respond naturally and keep the conversation moving.',
        supportLadder: ['Give only the communicative function.', 'Give a light meaning cue.', 'Reveal the target if needed, then change context for a fresh attempt.'],
      },
    },
    {
      id: 'fresh-maintained-conversation',
      title: 'Fresh conversation that genuinely keeps moving',
      goal: 'The learner can sustain a changed familiar conversation for several turns through active listening, relevant follow-up, acknowledgement, turn management, and selective use of lesson language without a supplied next question.',
      teaching: {
        explainInArabic: ['اعمل setup بس لموضوع مألوف جديد. الهدف conversation حقيقية، مش checklist كلمات.'],
        englishTargets: [
          'sustained interaction',
          'relevant follow-up',
          'acknowledgement',
          'simple turn management',
          'natural retrieval of selected lesson phrases/words/support patterns',
          'polite invitation when context makes it useful',
        ],
        constraints: [
          'Use a new topic and changed details.',
          'No complete model or supplied next question before the learner acts.',
          'Keep the exchange going for several learner turns; one good response is not final mastery evidence.',
          'Create natural opportunities for several earlier targets, including at least one phrase, one decision/planning item, and one interaction-support move.',
          'If a polite invitation can fit naturally, steer the conversation toward a small next step without explicitly instructing the learner to use the formula.',
          'Do not force every source item into one exchange; all individual targets were checked earlier. Final success is integrated conversational continuity.',
          'If an earlier target looks weak in this final exchange, repair briefly and create a new conversational opportunity before finishing.',
        ],
      },
      interaction: {
        kind: 'fresh_transfer',
        setup: 'Start a new familiar conversation such as a course, club, small plan, old contact, or local activity. Add information gradually and let the learner carry initiative for several turns.',
        learnerTask: 'Keep this conversation going naturally from what I say, build on details, and manage the interaction without waiting for a script.',
        teacherMoves: [
          'Offer details that reward active listening rather than generic questions.',
          'Later introduce a plan or decision so earlier planning vocabulary can reappear.',
          'Create one relationship/contact/explanation opportunity.',
          'Allow a small invitation or next-step opportunity if it fits.',
          'Before finishing, if the learner has only responded passively, add another turn that requires initiative.',
        ],
        supportLadder: ['Give only a non-answer-bearing Arabic functional cue.', 'Name the missing function, not the exact English.', 'If you must supply wording, change the situation and get a fresh independent attempt.'],
      },
    },
  ],
};
