import type { CourseLessonDefinition, CourseUnitDefinition } from '../types';

const commonAnswerKinds = ['answer', 'continuation'] as const;
const interactiveAnswerKinds = ['answer', 'question', 'continuation'] as const;

export const B1_UNIT_1_ID = 'b1-u1-storytelling';

const setTheScene: CourseLessonDefinition = {
  id: 'b1-u1-l1-set-the-scene',
  unitId: B1_UNIT_1_ID,
  order: 1,
  title: 'Set the scene',
  subtitle: 'Help the listener know where they are before the action starts.',
  purpose: 'Open a familiar story with enough time, place and background for another person to follow naturally.',
  languageFocus: [
    'time and place anchors: yesterday, last weekend, at work, on the way home',
    'background language: I was…, we were…, it was…',
    'moving from background to the first event',
  ],
  beats: [
    {
      id: 'scene-teach',
      title: 'A story needs a starting picture',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Warmly explain that a listener follows a story more easily when they quickly know when it happened, where the speaker was, and what was already happening. Give one short natural example, not a grammar lecture.',
      board: {
        type: 'steps',
        title: 'Set the scene',
        items: [
          { title: 'When?', body: 'Last Friday · yesterday · a few weeks ago' },
          { title: 'Where?', body: 'At work · at home · on the train' },
          { title: 'What was happening?', body: 'I was waiting · we were talking · it was raining' },
        ],
      },
    },
    {
      id: 'scene-guided',
      title: 'Give the listener the opening picture',
      kind: 'guided_practice',
      completion: 'evidence',
      teachingBrief: 'Ask for the opening of a real or invented familiar story. Keep the task small: one or two connected sentences are enough.',
      prompt: 'Give me the beginning of a story: when was it, where were you, and what was happening?',
      capability: 'b1.story.set-scene',
      successEvidence: 'The learner establishes a comprehensible story context with at least two useful anchors among time, place, people, or background activity, rather than jumping straight into an unexplained event.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['Ask only for the missing anchor.', 'If the learner is searching for language, offer one starter such as “I was…” without supplying their story.'],
    },
    {
      id: 'scene-event-teach',
      title: 'Background and event do different jobs',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Contrast background with the event that moves the story. Use one compact example such as “I was walking home when my phone rang.” Emphasize meaning first; name the grammar only if useful.',
      board: {
        type: 'compare',
        title: 'Background → event',
        left: { title: 'What was happening', body: 'I was walking home.' },
        right: { title: 'What happened next', body: 'My phone rang.' },
      },
    },
    {
      id: 'scene-event-practice',
      title: 'Move from the scene into the action',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Invite the learner to extend the opening by adding the first event. Keep it conversational and react to the content.',
      prompt: 'Now add the first thing that happened and changed the situation.',
      capability: 'b1.story.scene-to-event',
      successEvidence: 'The learner connects the established background to a first event in a way that creates a clear story opening. Exact tense forms are not required if the time relationship is understandable, but target background/event language should be encouraged and repaired when it blocks clarity.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['Ask “What happened next?” if the learner stays only in background.', 'Recast one useful tense contrast rather than correcting every verb.'],
    },
    {
      id: 'scene-recap',
      title: 'Keep the opening simple',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Recap the lesson in a warm spoken sentence: give the listener a quick scene, then let the first event move the story. Mention one thing the learner did effectively if evidence exists, without exposing rubric language.',
      board: { type: 'note', title: 'Scene → first event', body: 'Give the listener a quick picture before the action moves.' },
    },
  ],
};

const sequenceEvents: CourseLessonDefinition = {
  id: 'b1-u1-l2-sequence-events',
  unitId: B1_UNIT_1_ID,
  order: 2,
  title: 'Put events in order',
  subtitle: 'Make the listener feel the story moving instead of hearing a list.',
  purpose: 'Link familiar events into a clear chronological sequence using simple spoken connectors and time relationships.',
  languageFocus: [
    'first, then, after that, later, eventually, in the end',
    'chronological control without overusing one connector',
    'short connected stretches rather than isolated sentences',
  ],
  beats: [
    {
      id: 'sequence-teach',
      title: 'Give the listener a path through the story',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Explain that story connectors are signposts, not decoration. Demonstrate a three-step mini-story with varied simple connectors.',
      board: {
        type: 'steps',
        title: 'Move the story forward',
        items: [
          { title: 'First', body: 'start the action' },
          { title: 'Then / after that', body: 'connect the middle' },
          { title: 'Eventually / in the end', body: 'show where it landed' },
        ],
      },
    },
    {
      id: 'sequence-guided',
      title: 'Connect three events',
      kind: 'guided_practice',
      completion: 'evidence',
      teachingBrief: 'Ask the learner to tell three simple events from a familiar or invented situation in a clear order. Do not require a long story.',
      prompt: 'Tell me three things that happened, in order, as one connected little story.',
      capability: 'b1.story.sequence-events',
      successEvidence: 'The learner communicates at least three events in an understandable chronological order and uses language or sentence structure that makes the sequence clear rather than presenting disconnected fragments.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If order is unclear, ask what happened first or after that.', 'Offer one connector starter, then let the learner continue.'],
    },
    {
      id: 'sequence-variety-teach',
      title: 'Do not make every sentence sound the same',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Show that “then” is useful but does not need to start every sentence. Model a short sequence using a time phrase, then, and in the end.',
      board: {
        type: 'examples',
        title: 'Simple variety',
        items: [
          { title: 'A few minutes later…' },
          { title: 'Then…' },
          { title: 'In the end…' },
        ],
      },
    },
    {
      id: 'sequence-conversation',
      title: 'Keep a real story moving',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask for a short sequence from something ordinary that happened recently or can be invented. React naturally and listen for story momentum.',
      prompt: 'Tell me a short sequence from a recent day — something small is fine. Help me feel what happened first, next, and finally.',
      capability: 'b1.story.connected-sequence',
      successEvidence: 'The learner sustains a short connected chronological stretch with enough linking or temporal language for the listener to follow the movement of the story without repeated clarification.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If the learner produces a list, ask one follow-up that makes two events connect.', 'Prioritize sequence clarity over perfect verb morphology.'],
    },
    {
      id: 'sequence-recap',
      title: 'Let the timeline do the work',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Recap that clear order makes simple English sound stronger. Highlight one connector or sequencing choice the learner used well when possible.',
      board: { type: 'note', title: 'Clear order > fancy language', body: 'A listener can forgive simple words if the story is easy to follow.' },
    },
  ],
};

const causeAndConsequence: CourseLessonDefinition = {
  id: 'b1-u1-l3-cause-consequence',
  unitId: B1_UNIT_1_ID,
  order: 3,
  title: 'Explain why it happened',
  subtitle: 'Connect events with reasons and consequences.',
  purpose: 'Add simple reasons, results and consequences so a story communicates meaning rather than only chronology.',
  languageFocus: [
    'because for reasons',
    'so / that’s why for results',
    'reason → event → consequence chains',
  ],
  beats: [
    {
      id: 'cause-teach',
      title: 'Reason and result point in different directions',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Explain the practical difference between because and so using one natural pair. Keep terminology light and show the relationship visually.',
      board: {
        type: 'compare',
        title: 'Reason ↔ result',
        left: { title: 'because', body: 'I was late because the train stopped.' },
        right: { title: 'so', body: 'The train stopped, so I was late.' },
      },
    },
    {
      id: 'cause-guided',
      title: 'Give the reason',
      kind: 'guided_practice',
      completion: 'evidence',
      teachingBrief: 'Give the learner one ordinary story event and ask them to add a believable reason, or let them use their own event.',
      prompt: 'Choose a simple event — real or invented — and tell me why it happened.',
      capability: 'b1.reasons.explain-cause',
      successEvidence: 'The learner communicates a relevant reason for an event using a clear causal relationship. Target reason language should be encouraged; equivalent comprehensible phrasing can count if the relationship is explicit.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['Ask “Why?” only once if the relationship is missing.', 'Contrast because and so with the learner’s own meaning if they reverse them.'],
    },
    {
      id: 'consequence-teach',
      title: 'Stories become meaningful when something changes',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Model a compact chain: cause, event, consequence. Explain that a consequence can be practical or emotional.',
      board: {
        type: 'steps',
        title: 'Cause → event → consequence',
        items: [
          { title: 'Why?', body: 'The train was delayed.' },
          { title: 'What happened?', body: 'I arrived late.' },
          { title: 'What changed?', body: 'So the meeting started without me.' },
        ],
      },
    },
    {
      id: 'cause-conversation',
      title: 'Connect what happened to what changed',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask the learner to extend a story with both a reason and a result or consequence. One connected stretch is enough.',
      prompt: 'Tell me about one event, why it happened, and what happened because of it.',
      capability: 'b1.story.cause-consequence',
      successEvidence: 'The learner communicates an event together with a relevant cause and a resulting consequence or next effect in a connected, comprehensible way.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If only cause is present, ask what happened as a result.', 'If only result is present, ask what caused it.'],
    },
    {
      id: 'cause-recap',
      title: 'Chronology tells us what; cause tells us why',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Recap the value of adding one clear reason and one consequence to a story. Mention a successful causal link the learner made when appropriate.',
      board: { type: 'note', title: 'What happened + why + what changed', body: 'That is often enough to make a simple story feel complete.' },
    },
  ],
};

const reactionAndDetail: CourseLessonDefinition = {
  id: 'b1-u1-l4-reaction-detail',
  unitId: B1_UNIT_1_ID,
  order: 4,
  title: 'React and add useful detail',
  subtitle: 'Make the story sound like it mattered to a real person.',
  purpose: 'Add feelings, reactions and selected concrete detail without drowning the listener in unnecessary information.',
  languageFocus: [
    'I was surprised / relieved / annoyed / nervous',
    'the surprising / difficult / funny part was…',
    'one concrete detail that supports the story point',
  ],
  beats: [
    {
      id: 'reaction-teach',
      title: 'A reaction tells the listener why the event mattered',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Explain that a story often becomes more human when the speaker adds a short reaction, not a long emotion vocabulary list. Model one event plus one reaction.',
      board: {
        type: 'examples',
        title: 'Add a reaction',
        items: [
          { title: 'I was really surprised.' },
          { title: 'I felt relieved.' },
          { title: 'The funny part was…' },
        ],
      },
    },
    {
      id: 'reaction-guided',
      title: 'Say how the event affected you',
      kind: 'guided_practice',
      completion: 'evidence',
      teachingBrief: 'Ask for a reaction to a familiar real or invented event. Accept simple language if the attitude is clear.',
      prompt: 'Think of an event in a story. How did you react, and why?',
      capability: 'b1.story.express-reaction',
      successEvidence: 'The learner communicates a relevant reaction, feeling, evaluation, or attitude and connects it sufficiently to the event for the listener to understand why it mattered.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If the learner only names an emotion, ask what made them feel that way.', 'Offer one adjective only when language search blocks the message.'],
    },
    {
      id: 'detail-teach',
      title: 'Useful detail is selective',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Contrast one useful concrete detail with a pile of irrelevant detail. Explain that the best detail helps the listener picture or understand the important moment.',
      board: {
        type: 'compare',
        title: 'Which detail helps?',
        left: { title: 'Useful', body: 'My phone was on 2% battery.' },
        right: { title: 'Noise', body: 'The case was blue and I bought it last year.' },
      },
    },
    {
      id: 'detail-conversation',
      title: 'Make one moment vivid',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask the learner to tell one story moment with a reaction and one useful detail. React as a listener, not an examiner.',
      prompt: 'Tell me one important moment from a story and add one detail that helps me picture it, plus your reaction.',
      capability: 'b1.story.reaction-detail',
      successEvidence: 'The learner develops a story moment with at least one relevant concrete detail and a reaction/evaluation, creating a more informative connected contribution rather than a bare event statement.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If there is too much detail, ask which detail mattered most.', 'If the story stays abstract, ask what the learner could see, hear, notice, or feel in that moment.'],
    },
    {
      id: 'reaction-recap',
      title: 'One reaction and one useful detail can be enough',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Recap the lesson without praising everything. Point out that selective detail and reaction make a connected B1 story easier to care about and follow.',
      board: { type: 'note', title: 'Event + useful detail + reaction', body: 'Add meaning, not noise.' },
    },
  ],
};

const followUpsAndRepair: CourseLessonDefinition = {
  id: 'b1-u1-l5-followups-repair',
  unitId: B1_UNIT_1_ID,
  order: 5,
  title: 'Handle follow-up questions',
  subtitle: 'Stay in the conversation when the listener asks something you did not prepare for.',
  purpose: 'Answer natural follow-ups, clarify meaning and repair a gap without abandoning the story.',
  languageFocus: [
    'What I mean is… / Let me say that another way…',
    'I’m not sure of the word, but…',
    'adding one useful detail in response to a follow-up',
  ],
  beats: [
    {
      id: 'repair-teach',
      title: 'Repair is a speaking skill, not a failure',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Explain that independent speakers keep going even when a word is missing or a listener is confused. Model a short self-repair without sounding scripted.',
      board: {
        type: 'examples',
        title: 'Keep going',
        items: [
          { title: 'What I mean is…' },
          { title: 'Let me say that another way…' },
          { title: 'I’m not sure of the word, but it’s like…' },
        ],
      },
    },
    {
      id: 'repair-guided',
      title: 'Clarify instead of giving up',
      kind: 'guided_practice',
      completion: 'evidence',
      teachingBrief: 'Use one genuine clarification request based on a simple story detail. Let the learner repeat, rephrase or explain around a missing word.',
      prompt: 'Tell me one small story detail. I may ask you to clarify one part — keep going even if you need different words.',
      capability: 'b1.interaction.repair-meaning',
      successEvidence: 'When clarification is needed, the learner repeats, rephrases, specifies, circumlocutes, or checks meaning sufficiently to restore shared understanding instead of abandoning the exchange.',
      acceptedResponseKinds: interactiveAnswerKinds,
      repairHints: ['Do not fake hearing problems; clarify something genuinely ambiguous.', 'If the learner freezes, remind them that describing around a missing word counts.'],
    },
    {
      id: 'followup-teach',
      title: 'A follow-up is an invitation to develop the story',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Show how a short follow-up answer can add a reason, detail, or reaction instead of only saying yes/no. Model one concise example.',
      board: {
        type: 'compare',
        title: 'Build the answer',
        left: { title: 'Bare', body: 'Yes, I was.' },
        right: { title: 'Developed', body: 'Yes — I was nervous because I had never done it before.' },
      },
    },
    {
      id: 'followup-conversation',
      title: 'Answer something you did not rehearse',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask one natural unprepared follow-up about the learner’s story. It should require a little development, not a trick answer.',
      prompt: 'I’m going to ask one natural follow-up about your story. Answer it in enough detail to keep us talking.',
      capability: 'b1.interaction.handle-followup',
      successEvidence: 'The learner handles an unprepared familiar-topic follow-up with a relevant answer, clarification, or repair that develops the exchange beyond a bare acknowledgement.',
      acceptedResponseKinds: interactiveAnswerKinds,
      repairHints: ['Ask only one follow-up at a time.', 'Accept uncertainty if the learner can still explain what they know or mean.'],
    },
    {
      id: 'followup-recap',
      title: 'Independent speaking includes recovery',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Recap that B1 independence is not perfect fluency: it is the ability to keep meaning moving through pauses, follow-ups and repair. Mention one recovery move the learner used well if available.',
      board: { type: 'note', title: 'Keep meaning moving', body: 'Pause. Rephrase. Clarify. Continue.' },
    },
  ],
};

const storyChallenge: CourseLessonDefinition = {
  id: 'b1-u1-l6-story-challenge',
  unitId: B1_UNIT_1_ID,
  order: 6,
  title: 'Live story challenge',
  subtitle: 'Put the whole unit together in one unscripted conversation.',
  purpose: 'Produce a connected familiar narrative, explain reasons and reactions, and handle a genuine follow-up without the teacher walking through the skill one piece at a time.',
  languageFocus: [
    'scene setting',
    'chronological sequencing',
    'cause and consequence',
    'reaction and useful detail',
    'follow-up and repair',
  ],
  challenge: true,
  beats: [
    {
      id: 'challenge-setup',
      title: 'Tell a story people can follow',
      kind: 'teach',
      completion: 'teacher_turn',
      teachingBrief: 'Set up the challenge warmly. Invite a real or invented familiar story about something unexpected, inconvenient, funny, or memorable. Explain that you will listen like a real conversation partner and ask a follow-up later. Do not preview the hidden evidence checklist.',
      board: {
        type: 'steps',
        title: 'Your story',
        items: [
          { title: 'Set the scene' },
          { title: 'Move through the events' },
          { title: 'Explain why it mattered' },
          { title: 'Handle the follow-up' },
        ],
      },
    },
    {
      id: 'challenge-scene',
      title: 'Establish the story',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Invite the learner to begin naturally. Do not coach the unit steps unless repair is needed.',
      prompt: 'Tell me about something unexpected that happened — real or invented. Start wherever feels natural.',
      capability: 'b1.story.connected-narrative',
      successEvidence: 'The learner establishes enough familiar context and begins a connected narrative that a listener can follow without the teacher supplying the story structure.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['If the opening is too context-free, ask one genuine orienting question.', 'Do not make the learner restart a usable opening.'],
    },
    {
      id: 'challenge-sequence',
      title: 'Keep the story moving',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Let the learner continue. Use one natural follow-up only if needed to reveal chronology.',
      prompt: 'And what happened after that?',
      capability: 'b1.story.connected-sequence',
      successEvidence: 'The learner links multiple events into a comprehensible chronological sequence, maintaining story momentum with simple connecting or temporal language.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['Clarify order only when the listener genuinely cannot follow.', 'Do not require a particular connector.'],
    },
    {
      id: 'challenge-meaning',
      title: 'Explain why it mattered',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask a natural question that invites cause, consequence, or reaction based on what the learner actually said.',
      prompt: 'Why did that matter, or how did you react?',
      capability: 'b1.story.reasoned-response',
      successEvidence: 'The learner adds a relevant reason, consequence, reaction, or evaluation that develops the narrative beyond a sequence of events.',
      acceptedResponseKinds: commonAnswerKinds,
      repairHints: ['Accept either cause, consequence, or reaction if it meaningfully develops the story.', 'Ask for one concrete reason or reaction rather than several.'],
    },
    {
      id: 'challenge-followup',
      title: 'Handle a real follow-up',
      kind: 'conversation_task',
      completion: 'evidence',
      teachingBrief: 'Ask one genuine unprepared question based on the learner’s story. Let repair or circumlocution count when it preserves meaning.',
      prompt: 'Ask one natural follow-up that you genuinely want answered based on the story so far.',
      capability: 'b1.interaction.handle-followup',
      successEvidence: 'The learner responds to an unprepared familiar-topic follow-up with enough relevant meaning, clarification, or repair to keep the exchange moving.',
      acceptedResponseKinds: interactiveAnswerKinds,
      repairHints: ['Do not ask trivia or a memory test.', 'If a word is missing, give space for circumlocution before helping.'],
    },
    {
      id: 'challenge-recap',
      title: 'Close the unit with evidence, not a score',
      kind: 'recap',
      completion: 'teacher_turn',
      teachingBrief: 'Give a concise spoken recap of what came through in the conversation and one useful next focus if needed. Do not give a numeric score or claim B1 mastery. Treat this as one fresh story observation.',
      board: { type: 'note', title: 'One complete story', body: 'Clear scene · connected events · meaning · real follow-up' },
    },
  ],
};

export const B1_UNIT_1_LESSONS = [
  setTheScene,
  sequenceEvents,
  causeAndConsequence,
  reactionAndDetail,
  followUpsAndRepair,
  storyChallenge,
] as const satisfies readonly CourseLessonDefinition[];

export const B1_UNIT_1: CourseUnitDefinition = {
  id: B1_UNIT_1_ID,
  levelId: 'b1',
  order: 1,
  title: 'Tell stories people can follow',
  promise: 'Build connected familiar stories, explain what changed, and stay in the conversation when the listener asks something unexpected.',
  lessons: B1_UNIT_1_LESSONS,
};
